// Umbrella header for the generated ONDEWO gRPC C++ client stubs.
//
// Seeded from image-data/default-lib-files/public-api.h and completed by
// make-lib-entry-point.sh, which appends one #include per generated *.pb.h and
// *.grpc.pb.h below (paths are relative to the api/ include root).
//
// Provide your own public-api.h in the mounted input volume to take over this file
// completely - it is then used verbatim and nothing is appended.

#pragma once

#include "google/api/annotations.grpc.pb.h"
#include "google/api/annotations.pb.h"
#include "google/api/http.grpc.pb.h"
#include "google/api/http.pb.h"
#include "google/rpc/status.grpc.pb.h"
#include "google/rpc/status.pb.h"
#include "google/type/latlng.grpc.pb.h"
#include "google/type/latlng.pb.h"
#include "ondewo/nlu/agent.grpc.pb.h"
#include "ondewo/nlu/agent.pb.h"
#include "ondewo/nlu/aiservices.grpc.pb.h"
#include "ondewo/nlu/aiservices.pb.h"
#include "ondewo/nlu/ccai_project.grpc.pb.h"
#include "ondewo/nlu/ccai_project.pb.h"
#include "ondewo/nlu/common.grpc.pb.h"
#include "ondewo/nlu/common.pb.h"
#include "ondewo/nlu/context.grpc.pb.h"
#include "ondewo/nlu/context.pb.h"
#include "ondewo/nlu/entity_type.grpc.pb.h"
#include "ondewo/nlu/entity_type.pb.h"
#include "ondewo/nlu/intent.grpc.pb.h"
#include "ondewo/nlu/intent.pb.h"
#include "ondewo/nlu/llm_evaluation.grpc.pb.h"
#include "ondewo/nlu/llm_evaluation.pb.h"
#include "ondewo/nlu/operation_metadata.grpc.pb.h"
#include "ondewo/nlu/operation_metadata.pb.h"
#include "ondewo/nlu/operations.grpc.pb.h"
#include "ondewo/nlu/operations.pb.h"
#include "ondewo/nlu/project_role.grpc.pb.h"
#include "ondewo/nlu/project_role.pb.h"
#include "ondewo/nlu/project_statistics.grpc.pb.h"
#include "ondewo/nlu/project_statistics.pb.h"
#include "ondewo/nlu/rag.grpc.pb.h"
#include "ondewo/nlu/rag.pb.h"
#include "ondewo/nlu/server_statistics.grpc.pb.h"
#include "ondewo/nlu/server_statistics.pb.h"
#include "ondewo/nlu/session.grpc.pb.h"
#include "ondewo/nlu/session.pb.h"
#include "ondewo/nlu/user.grpc.pb.h"
#include "ondewo/nlu/user.pb.h"
#include "ondewo/nlu/utility.grpc.pb.h"
#include "ondewo/nlu/utility.pb.h"
#include "ondewo/nlu/webhook.grpc.pb.h"
#include "ondewo/nlu/webhook.pb.h"
#include "ondewo/qa/qa.grpc.pb.h"
#include "ondewo/qa/qa.pb.h"
#include "ondewo/s2t/speech-to-text.grpc.pb.h"
#include "ondewo/s2t/speech-to-text.pb.h"
#include "ondewo/sip/sip.grpc.pb.h"
#include "ondewo/sip/sip.pb.h"
#include "ondewo/t2s/text-to-speech.grpc.pb.h"
#include "ondewo/t2s/text-to-speech.pb.h"
#include "ondewo/vtsi/calls.grpc.pb.h"
#include "ondewo/vtsi/calls.pb.h"
#include "ondewo/vtsi/logs.grpc.pb.h"
#include "ondewo/vtsi/logs.pb.h"
#include "ondewo/vtsi/projects.grpc.pb.h"
#include "ondewo/vtsi/projects.pb.h"
