// TLS / mutual TLS through ondewo/client/channel.h, against real in-process gRPC servers.
//
// Product-agnostic: nothing here names a generated type, so the file is copied verbatim
// between the ONDEWO C++ clients. Every handshake test issues a real RPC (the default health
// method, answered by a generic callback service): an OK answer proves the handshake completed,
// UNAVAILABLE that it was refused - and in neither case may the process crash.
//
// The PKI (a CA, a server certificate for localhost / 127.0.0.1 / ::1, a client certificate,
// and a second, unrelated CA with a client certificate of its own) is generated by the openssl
// CLI into a temporary directory at test time. No private key is committed.

#include <unistd.h>

#include <chrono>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <map>
#include <memory>
#include <sstream>
#include <string>

#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/generic/generic_stub.h>
#include <grpcpp/grpcpp.h>
#include <gtest/gtest.h>

#include <ondewo/client/channel.h>

namespace ondewo_client_test {
namespace {

using ondewo::client::ClientConfig;

// The PEMs of one CA and the leaves it signed.
struct Pki {
  std::string ca;
  std::string server_cert;
  std::string server_key;
  std::string client_cert;
  std::string client_key;
};

std::string ReadFile(const std::filesystem::path& path) {
  std::ifstream in(path, std::ios::binary);
  return std::string(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
}

// Generated once per test process (CTest runs every TEST in a process of its own), with the
// same openssl commands the README documents.
class TestPki {
 public:
  static const TestPki& Get() {
    static const TestPki pki;
    return pki;
  }

  Pki own;
  Pki foreign;

 private:
  TestPki() {
    char dir_template[] = "/tmp/ondewo-tls-test-XXXXXX";
    const std::filesystem::path dir = mkdtemp(dir_template);
    std::ofstream(dir / "pki.sh") << R"(set -e
cd "$1"
ca() {
  openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 -nodes -days 2 \
    -subj "/CN=$1" -keyout "$1.key" -out "$1.pem"
}
leaf() {
  printf "$4" > "$1.ext"
  openssl req -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 -nodes \
    -subj "/CN=$2" -keyout "$1.key" -out "$1.csr"
  openssl x509 -req -in "$1.csr" -CA "$3.pem" -CAkey "$3.key" -CAcreateserial -days 2 \
    -extfile "$1.ext" -out "$1.pem"
}
ca ca
ca foreign-ca
leaf server localhost ca 'subjectAltName=DNS:localhost,IP:127.0.0.1,IP:::1\nextendedKeyUsage=serverAuth\n'
leaf client my-client ca 'extendedKeyUsage=clientAuth\n'
leaf foreign-client my-client foreign-ca 'extendedKeyUsage=clientAuth\n'
)";
    const std::string command = "sh " + (dir / "pki.sh").string() + " " + dir.string() + " > " +
                                (dir / "pki.log").string() + " 2>&1";
    EXPECT_EQ(std::system(command.c_str()), 0) << ReadFile(dir / "pki.log");
    own = {ReadFile(dir / "ca.pem"), ReadFile(dir / "server.pem"), ReadFile(dir / "server.key"),
           ReadFile(dir / "client.pem"), ReadFile(dir / "client.key")};
    foreign = {ReadFile(dir / "foreign-ca.pem"), "", "", ReadFile(dir / "foreign-client.pem"),
               ReadFile(dir / "foreign-client.key")};
    std::filesystem::remove_all(dir);
  }
};

// Answers every method with one empty message and OK, whatever the request. Generic, so the
// suite needs no service of its own and no generated type.
class AnswerEverything : public grpc::CallbackGenericService {
  grpc::ServerGenericBidiReactor* CreateReactor(grpc::GenericCallbackServerContext*) override {
    class Reactor : public grpc::ServerGenericBidiReactor {
     public:
      Reactor() { StartWriteAndFinish(&response_, grpc::WriteOptions(), grpc::Status::OK); }
      void OnDone() override { delete this; }

     private:
      grpc::Slice empty_{""};
      grpc::ByteBuffer response_{&empty_, 1};
    };
    return new Reactor;
  }
};

// An in-process server answering every method. TLS with the own PKI's server
// certificate, optionally requiring a client certificate signed by the own CA; or plaintext.
class TestServer {
 public:
  enum class Mode { kInsecure, kTls, kMutualTls };

  explicit TestServer(Mode mode, const std::string& address = "127.0.0.1:0") {
    const Pki& pki = TestPki::Get().own;
    grpc::SslServerCredentialsOptions options(mode == Mode::kMutualTls
                                                  ? GRPC_SSL_REQUEST_AND_REQUIRE_CLIENT_CERTIFICATE_AND_VERIFY
                                                  : GRPC_SSL_DONT_REQUEST_CLIENT_CERTIFICATE);
    options.pem_root_certs = pki.ca;
    options.pem_key_cert_pairs.push_back({pki.server_key, pki.server_cert});
    grpc::ServerBuilder builder;
    builder.RegisterCallbackGenericService(&service);
    builder.AddListeningPort(address,
                             mode == Mode::kInsecure ? grpc::InsecureServerCredentials()
                                                     : grpc::SslServerCredentials(options),
                             &port);
    server = builder.BuildAndStart();
  }

  ~TestServer() {
    if (server) server->Shutdown(std::chrono::system_clock::now());
  }

  // Declared before the server, so it outlives it.
  AnswerEverything service;
  int port = 0;
  std::unique_ptr<grpc::Server> server;
};

ClientConfig Config(const TestServer& server, const std::string& ca, const std::string& client_cert = "",
                    const std::string& client_key = "", const std::string& host = "127.0.0.1") {
  ClientConfig config;
  config.host = host;
  config.port = std::to_string(server.port);
  config.grpc_cert = ca;
  config.grpc_client_cert = client_cert;
  config.grpc_client_key = client_key;
  return config;
}

// One unary RPC; its status says whether the call reached the server.
grpc::Status Check(const std::shared_ptr<grpc::Channel>& channel) {
  grpc::GenericStub stub(channel);
  grpc::CompletionQueue queue;
  grpc::ClientContext context;
  context.set_deadline(std::chrono::system_clock::now() + std::chrono::seconds(10));
  grpc::Slice empty("");
  const grpc::ByteBuffer request(&empty, 1);
  grpc::ByteBuffer response;
  grpc::Status status;
  auto call = stub.PrepareUnaryCall(&context, "/ondewo.test.Tls/Check", request, &queue);
  call->StartCall();
  call->Finish(&response, &status, nullptr);
  void* tag = nullptr;
  bool ok = false;
  EXPECT_TRUE(queue.Next(&tag, &ok));
  queue.Shutdown();
  while (queue.Next(&tag, &ok)) continue;
  return status;
}

grpc::Status Connect(const ClientConfig& config) {
  std::shared_ptr<grpc::Channel> channel;
  const grpc::Status created = ondewo::client::CreateChannel(config, &channel);
  EXPECT_TRUE(created.ok()) << created.error_message();
  return Check(channel);
}

std::string ToCrlf(const std::string& pem) {
  std::string out;
  for (const char c : pem) out += c == '\n' ? std::string("\r\n") : std::string(1, c);
  return out;
}

// Stand-ins for PEM content in the tests that never reach gRPC. The key's marker is split into two
// literals so the detect-private-key pre-commit hook does not mistake this file for a key.
constexpr const char* kFakeCert = "-----BEGIN CERTIFICATE-----cert-content";
constexpr const char* kFakeKey = "-----BEGIN " "PRIVATE KEY-----key-content";

// No error message and no rendering may carry key or certificate material.
void ExpectNoSecret(const std::string& text) {
  EXPECT_EQ(text.find("BEGIN"), std::string::npos) << text;
  EXPECT_EQ(text.find("PRIVATE"), std::string::npos) << text;
  EXPECT_EQ(text.find("cert-content"), std::string::npos) << text;
  EXPECT_EQ(text.find("key-content"), std::string::npos) << text;
}

// ------------------------------------------------------------------------------------------
// Configuration: no gRPC involved

TEST(TlsConfig, HostAndPortBracketsBareIpv6LiteralsOnly) {
  ClientConfig config;
  config.port = "50051";
  const std::map<std::string, std::string> expected = {
      {"localhost", "localhost:50051"},
      {"10.0.0.5", "10.0.0.5:50051"},
      {"::1", "[::1]:50051"},
      {"2001:db8::17", "[2001:db8::17]:50051"},
      {"::ffff:10.0.0.5", "[::ffff:10.0.0.5]:50051"},
      {"fe80::1%eth0", "[fe80::1%eth0]:50051"},
      {"[::1]", "[::1]:50051"},
      {"ipv6:[::1]", "ipv6:[::1]:50051"},
      {"dns:///nlu.example.com", "dns:///nlu.example.com:50051"},
      {"cafe", "cafe:50051"},
  };
  for (const auto& [host, host_and_port] : expected) {
    config.host = host;
    EXPECT_EQ(config.HostAndPort(), host_and_port) << host;
  }
}

TEST(TlsConfig, ToStringRedactsTheKeyAndPrintsNoPem) {
  ClientConfig config;
  config.host = "nlu.example.com";
  config.port = "443";
  config.grpc_cert = "-----BEGIN CERTIFICATE-----ca-cert-content";
  config.grpc_client_cert = kFakeCert;
  config.grpc_client_key = kFakeKey;
  const std::string text = config.ToString();
  EXPECT_NE(text.find("grpc_client_key=***REDACTED***"), std::string::npos) << text;
  EXPECT_NE(text.find("nlu.example.com"), std::string::npos) << text;
  ExpectNoSecret(text);
  std::ostringstream streamed;
  streamed << config;
  EXPECT_EQ(streamed.str(), text);
}

TEST(TlsConfig, ToStringRendersAnEmptyKeyEmpty) {
  ClientConfig config;
  config.use_secure_channel = false;
  const std::string text = config.ToString();
  EXPECT_NE(text.find("grpc_client_key=,"), std::string::npos) << text;
  EXPECT_EQ(text.find("REDACTED"), std::string::npos) << text;
  EXPECT_NE(text.find("use_secure_channel=false"), std::string::npos) << text;
}

TEST(TlsConfig, HalfAClientIdentityIsRefusedBeforeGrpc) {
  for (const bool cert_only : {true, false}) {
    ClientConfig config;
    config.host = "::1";
    config.port = "50051";
    (cert_only ? config.grpc_client_cert : config.grpc_client_key) = cert_only ? kFakeCert : kFakeKey;
    std::shared_ptr<grpc::Channel> channel;
    const grpc::Status status = ondewo::client::CreateChannel(config, &channel);
    EXPECT_EQ(status.error_code(), grpc::StatusCode::INVALID_ARGUMENT);
    EXPECT_NE(status.error_message().find("only one of grpc_client_cert and grpc_client_key"), std::string::npos);
    EXPECT_NE(status.error_message().find("[::1]:50051"), std::string::npos) << status.error_message();
    ExpectNoSecret(status.error_message());
    EXPECT_EQ(channel, nullptr);
    std::shared_ptr<grpc::ChannelCredentials> credentials;
    EXPECT_FALSE(ondewo::client::CreateChannelCredentials(config, &credentials).ok());
    EXPECT_EQ(credentials, nullptr);
  }
}

TEST(TlsConfig, AnInsecureChannelWithAClientIdentityIsRefused) {
  ClientConfig config;
  config.host = "nlu.example.com";
  config.port = "50051";
  config.grpc_client_cert = kFakeCert;
  config.grpc_client_key = kFakeKey;
  config.use_secure_channel = false;
  std::shared_ptr<grpc::Channel> channel;
  const grpc::Status status = ondewo::client::CreateChannel(config, &channel);
  EXPECT_EQ(status.error_code(), grpc::StatusCode::INVALID_ARGUMENT);
  EXPECT_NE(status.error_message().find("use_secure_channel is false"), std::string::npos);
  EXPECT_NE(status.error_message().find("nlu.example.com:50051"), std::string::npos);
  ExpectNoSecret(status.error_message());
  EXPECT_EQ(channel, nullptr);
}

TEST(TlsConfig, DefaultChannelArgumentsMatchTheOtherSdks) {
  const grpc::ChannelArguments args = ondewo::client::DefaultChannelArguments();
  grpc_channel_args raw;
  args.SetChannelArgs(&raw);
  std::map<std::string, int> ints;
  for (size_t i = 0; i < raw.num_args; ++i)
    if (raw.args[i].type == GRPC_ARG_INTEGER) ints[raw.args[i].key] = raw.args[i].value.integer;
  const std::map<std::string, int> expected = {
      {GRPC_ARG_MAX_SEND_MESSAGE_LENGTH, 2147483647},
      {GRPC_ARG_MAX_RECEIVE_MESSAGE_LENGTH, 2147483647},
      {GRPC_ARG_KEEPALIVE_TIME_MS, 30000},
      {GRPC_ARG_KEEPALIVE_TIMEOUT_MS, 20000},
      {GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS, 0},
      {GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA, 2},
      {"grpc.http2.ping_timeout_ms", 20000},
      {GRPC_ARG_MAX_RECONNECT_BACKOFF_MS, 5000},
  };
  for (const auto& [key, value] : expected) EXPECT_EQ(ints[key], value) << key;
}

// ------------------------------------------------------------------------------------------
// Real handshakes

TEST(TlsHandshake, PlainTlsReachesTheServer) {
  const TestServer server(TestServer::Mode::kTls);
  const grpc::Status status = Connect(Config(server, TestPki::Get().own.ca));
  EXPECT_TRUE(status.ok()) << status.error_code() << " " << status.error_message();
}

TEST(TlsHandshake, EmptyStringsOnBothIdentityFieldsArePlainTls) {
  const TestServer server(TestServer::Mode::kTls);
  EXPECT_TRUE(Connect(Config(server, TestPki::Get().own.ca, "", "")).ok());
}

TEST(TlsHandshake, MutualTlsWithALeafFromTheServersCaIsServed) {
  const TestServer server(TestServer::Mode::kMutualTls);
  const Pki& pki = TestPki::Get().own;
  EXPECT_TRUE(Connect(Config(server, pki.ca, pki.client_cert, pki.client_key)).ok());
}

TEST(TlsHandshake, ATlsOnlyServerAlsoServesAClientPresentingALeaf) {
  const TestServer server(TestServer::Mode::kTls);
  const Pki& pki = TestPki::Get().own;
  EXPECT_TRUE(Connect(Config(server, pki.ca, pki.client_cert, pki.client_key)).ok());
}

TEST(TlsHandshake, MutualTlsWithoutAClientLeafIsRefused) {
  const TestServer server(TestServer::Mode::kMutualTls);
  EXPECT_EQ(Connect(Config(server, TestPki::Get().own.ca)).error_code(), grpc::StatusCode::UNAVAILABLE);
}

TEST(TlsHandshake, AClientLeafFromAnUnrelatedCaIsRefused) {
  const TestServer server(TestServer::Mode::kMutualTls);
  const Pki& foreign = TestPki::Get().foreign;
  EXPECT_EQ(Connect(Config(server, TestPki::Get().own.ca, foreign.client_cert, foreign.client_key)).error_code(),
            grpc::StatusCode::UNAVAILABLE);
}

TEST(TlsHandshake, TheWrongCaFailsTheHandshakeWithoutACrash) {
  const TestServer server(TestServer::Mode::kTls);
  EXPECT_EQ(Connect(Config(server, TestPki::Get().foreign.ca)).error_code(), grpc::StatusCode::UNAVAILABLE);
}

TEST(TlsHandshake, TheSystemTrustStoreDoesNotTrustAPrivateCa) {
  const TestServer server(TestServer::Mode::kTls);
  EXPECT_EQ(Connect(Config(server, "")).error_code(), grpc::StatusCode::UNAVAILABLE);
}

TEST(TlsHandshake, ANonPemCaIsAnErrorNotACrash) {
  const TestServer server(TestServer::Mode::kTls);
  EXPECT_EQ(Connect(Config(server, "certs/ca.pem")).error_code(), grpc::StatusCode::UNAVAILABLE);
}

TEST(TlsHandshake, CrlfPemsCompleteTheMutualTlsHandshake) {
  const TestServer server(TestServer::Mode::kMutualTls);
  const Pki& pki = TestPki::Get().own;
  ASSERT_NE(ToCrlf(pki.client_key).find("\r\n"), std::string::npos);
  EXPECT_TRUE(Connect(Config(server, ToCrlf(pki.ca), ToCrlf(pki.client_cert), ToCrlf(pki.client_key))).ok());
}

TEST(TlsHandshake, TheServerNameIsVerifiedAndCanBeOverridden) {
  const TestServer server(TestServer::Mode::kTls);
  const ClientConfig config = Config(server, TestPki::Get().own.ca);
  for (const auto& [name, expected] : std::map<std::string, grpc::StatusCode>{
           {"localhost", grpc::StatusCode::OK}, {"nlu.example.com", grpc::StatusCode::UNAVAILABLE}}) {
    grpc::ChannelArguments args = ondewo::client::DefaultChannelArguments();
    args.SetSslTargetNameOverride(name);
    std::shared_ptr<grpc::Channel> channel;
    EXPECT_TRUE(ondewo::client::CreateChannel(config, args, &channel).ok());
    EXPECT_EQ(Check(channel).error_code(), expected) << name;
  }
}

TEST(TlsHandshake, ABareIpv6LiteralHostConnects) {
  const TestServer server(TestServer::Mode::kMutualTls, "[::1]:0");
  if (server.port == 0) GTEST_SKIP() << "no IPv6 loopback in this environment";
  const Pki& pki = TestPki::Get().own;
  EXPECT_TRUE(Connect(Config(server, pki.ca, pki.client_cert, pki.client_key, "::1")).ok());
}

TEST(TlsHandshake, AnInsecureChannelWarnsNamingHostAndPort) {
  const TestServer server(TestServer::Mode::kInsecure);
  ClientConfig config = Config(server, "");
  config.use_secure_channel = false;
  std::ostringstream captured;
  std::streambuf* const original = std::clog.rdbuf(captured.rdbuf());
  const grpc::Status status = Connect(config);
  std::clog.rdbuf(original);
  EXPECT_TRUE(status.ok()) << status.error_message();
  EXPECT_NE(captured.str().find("INSECURE"), std::string::npos) << captured.str();
  EXPECT_NE(captured.str().find("127.0.0.1:" + config.port), std::string::npos) << captured.str();
}

}  // namespace
}  // namespace ondewo_client_test
