// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ondewo/vtsi/logs.proto
// Original file comments:
// Copyright 2021 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_ondewo_2fvtsi_2flogs_2eproto__INCLUDED
#define GRPC_ondewo_2fvtsi_2flogs_2eproto__INCLUDED

#include "ondewo/vtsi/logs.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ondewo {
namespace vtsi {

// <p>ONDEWO VTSI API</p>
class Logs final {
 public:
  static constexpr char const* service_full_name() {
    return "ondewo.vtsi.Logs";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // ////////////////////////////////////////////////////////////////////////////
    // Call log endpoints
    // ////////////////////////////////////////////////////////////////////////////
    //
    // <p>Streams the container logs of the ondewo-sip / ondewo-csi containers of a VTSI project as
    // they are captured, in the manner of <code>docker logs --follow</code>. The stream replays
    // <code>tail_lines</code> historical entries and then follows. It stays open until the capture
    // of every matching log stream has terminated, until the client disconnects, or until the
    // server-side maximum stream duration is reached.</p>
    // <p>Entries are served from the VTSI database rather than from the docker daemon, so a
    // container that has already been removed still streams. Secrets are redacted server-side.</p>
    std::unique_ptr< ::grpc::ClientReaderInterface< ::ondewo::vtsi::StreamCallLogsResponse>> StreamCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::ondewo::vtsi::StreamCallLogsResponse>>(StreamCallLogsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ondewo::vtsi::StreamCallLogsResponse>> AsyncStreamCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ondewo::vtsi::StreamCallLogsResponse>>(AsyncStreamCallLogsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ondewo::vtsi::StreamCallLogsResponse>> PrepareAsyncStreamCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ondewo::vtsi::StreamCallLogsResponse>>(PrepareAsyncStreamCallLogsRaw(context, request, cq));
    }
    // <p>Returns a bounded, filtered page of captured container log entries. Supports a time window,
    // severity filtering, a regular expression, a plain-text search and cursor paging in both
    // directions for infinite scrolling. Secrets are redacted server-side.</p>
    virtual ::grpc::Status ListCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest& request, ::ondewo::vtsi::ListCallLogsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogsResponse>> AsyncListCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogsResponse>>(AsyncListCallLogsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogsResponse>> PrepareAsyncListCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogsResponse>>(PrepareAsyncListCallLogsRaw(context, request, cq));
    }
    // <p>Returns the capture state of a single log stream, i.e. of one capture generation of one
    // container.</p>
    virtual ::grpc::Status GetCallLogStream(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest& request, ::ondewo::vtsi::CallLogStream* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::CallLogStream>> AsyncGetCallLogStream(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::CallLogStream>>(AsyncGetCallLogStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::CallLogStream>> PrepareAsyncGetCallLogStream(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::CallLogStream>>(PrepareAsyncGetCallLogStreamRaw(context, request, cq));
    }
    // <p>Lists the log streams VTSI has captured for a project. A single container yields a new log
    // stream every time it is recreated, because a recreated container is a new docker container
    // whose previous logs no longer exist.</p>
    virtual ::grpc::Status ListCallLogStreams(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest& request, ::ondewo::vtsi::ListCallLogStreamsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogStreamsResponse>> AsyncListCallLogStreams(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogStreamsResponse>>(AsyncListCallLogStreamsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogStreamsResponse>> PrepareAsyncListCallLogStreams(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogStreamsResponse>>(PrepareAsyncListCallLogStreamsRaw(context, request, cq));
    }
    // <p>Permanently deletes captured log entries matching a filter. This is the erasure path for
    // data-subject requests: retention answers &quot;delete everything older than N days&quot;, this
    // answers &quot;delete everything for this call or this phone number&quot;.</p>
    virtual ::grpc::Status DeleteCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest& request, ::ondewo::vtsi::DeleteCallLogsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::DeleteCallLogsResponse>> AsyncDeleteCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::DeleteCallLogsResponse>>(AsyncDeleteCallLogsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::DeleteCallLogsResponse>> PrepareAsyncDeleteCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::DeleteCallLogsResponse>>(PrepareAsyncDeleteCallLogsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // ////////////////////////////////////////////////////////////////////////////
      // Call log endpoints
      // ////////////////////////////////////////////////////////////////////////////
      //
      // <p>Streams the container logs of the ondewo-sip / ondewo-csi containers of a VTSI project as
      // they are captured, in the manner of <code>docker logs --follow</code>. The stream replays
      // <code>tail_lines</code> historical entries and then follows. It stays open until the capture
      // of every matching log stream has terminated, until the client disconnects, or until the
      // server-side maximum stream duration is reached.</p>
      // <p>Entries are served from the VTSI database rather than from the docker daemon, so a
      // container that has already been removed still streams. Secrets are redacted server-side.</p>
      virtual void StreamCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest* request, ::grpc::ClientReadReactor< ::ondewo::vtsi::StreamCallLogsResponse>* reactor) = 0;
      // <p>Returns a bounded, filtered page of captured container log entries. Supports a time window,
      // severity filtering, a regular expression, a plain-text search and cursor paging in both
      // directions for infinite scrolling. Secrets are redacted server-side.</p>
      virtual void ListCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest* request, ::ondewo::vtsi::ListCallLogsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest* request, ::ondewo::vtsi::ListCallLogsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // <p>Returns the capture state of a single log stream, i.e. of one capture generation of one
      // container.</p>
      virtual void GetCallLogStream(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest* request, ::ondewo::vtsi::CallLogStream* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCallLogStream(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest* request, ::ondewo::vtsi::CallLogStream* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // <p>Lists the log streams VTSI has captured for a project. A single container yields a new log
      // stream every time it is recreated, because a recreated container is a new docker container
      // whose previous logs no longer exist.</p>
      virtual void ListCallLogStreams(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest* request, ::ondewo::vtsi::ListCallLogStreamsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListCallLogStreams(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest* request, ::ondewo::vtsi::ListCallLogStreamsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // <p>Permanently deletes captured log entries matching a filter. This is the erasure path for
      // data-subject requests: retention answers &quot;delete everything older than N days&quot;, this
      // answers &quot;delete everything for this call or this phone number&quot;.</p>
      virtual void DeleteCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest* request, ::ondewo::vtsi::DeleteCallLogsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest* request, ::ondewo::vtsi::DeleteCallLogsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::ondewo::vtsi::StreamCallLogsResponse>* StreamCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::ondewo::vtsi::StreamCallLogsResponse>* AsyncStreamCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::ondewo::vtsi::StreamCallLogsResponse>* PrepareAsyncStreamCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogsResponse>* AsyncListCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogsResponse>* PrepareAsyncListCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::CallLogStream>* AsyncGetCallLogStreamRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::CallLogStream>* PrepareAsyncGetCallLogStreamRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogStreamsResponse>* AsyncListCallLogStreamsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::ListCallLogStreamsResponse>* PrepareAsyncListCallLogStreamsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::DeleteCallLogsResponse>* AsyncDeleteCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::vtsi::DeleteCallLogsResponse>* PrepareAsyncDeleteCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::ondewo::vtsi::StreamCallLogsResponse>> StreamCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::ondewo::vtsi::StreamCallLogsResponse>>(StreamCallLogsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::ondewo::vtsi::StreamCallLogsResponse>> AsyncStreamCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::ondewo::vtsi::StreamCallLogsResponse>>(AsyncStreamCallLogsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::ondewo::vtsi::StreamCallLogsResponse>> PrepareAsyncStreamCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::ondewo::vtsi::StreamCallLogsResponse>>(PrepareAsyncStreamCallLogsRaw(context, request, cq));
    }
    ::grpc::Status ListCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest& request, ::ondewo::vtsi::ListCallLogsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogsResponse>> AsyncListCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogsResponse>>(AsyncListCallLogsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogsResponse>> PrepareAsyncListCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogsResponse>>(PrepareAsyncListCallLogsRaw(context, request, cq));
    }
    ::grpc::Status GetCallLogStream(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest& request, ::ondewo::vtsi::CallLogStream* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::CallLogStream>> AsyncGetCallLogStream(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::CallLogStream>>(AsyncGetCallLogStreamRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::CallLogStream>> PrepareAsyncGetCallLogStream(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::CallLogStream>>(PrepareAsyncGetCallLogStreamRaw(context, request, cq));
    }
    ::grpc::Status ListCallLogStreams(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest& request, ::ondewo::vtsi::ListCallLogStreamsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogStreamsResponse>> AsyncListCallLogStreams(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogStreamsResponse>>(AsyncListCallLogStreamsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogStreamsResponse>> PrepareAsyncListCallLogStreams(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogStreamsResponse>>(PrepareAsyncListCallLogStreamsRaw(context, request, cq));
    }
    ::grpc::Status DeleteCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest& request, ::ondewo::vtsi::DeleteCallLogsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::DeleteCallLogsResponse>> AsyncDeleteCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::DeleteCallLogsResponse>>(AsyncDeleteCallLogsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::DeleteCallLogsResponse>> PrepareAsyncDeleteCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::DeleteCallLogsResponse>>(PrepareAsyncDeleteCallLogsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest* request, ::grpc::ClientReadReactor< ::ondewo::vtsi::StreamCallLogsResponse>* reactor) override;
      void ListCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest* request, ::ondewo::vtsi::ListCallLogsResponse* response, std::function<void(::grpc::Status)>) override;
      void ListCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest* request, ::ondewo::vtsi::ListCallLogsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetCallLogStream(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest* request, ::ondewo::vtsi::CallLogStream* response, std::function<void(::grpc::Status)>) override;
      void GetCallLogStream(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest* request, ::ondewo::vtsi::CallLogStream* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListCallLogStreams(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest* request, ::ondewo::vtsi::ListCallLogStreamsResponse* response, std::function<void(::grpc::Status)>) override;
      void ListCallLogStreams(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest* request, ::ondewo::vtsi::ListCallLogStreamsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest* request, ::ondewo::vtsi::DeleteCallLogsResponse* response, std::function<void(::grpc::Status)>) override;
      void DeleteCallLogs(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest* request, ::ondewo::vtsi::DeleteCallLogsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::ondewo::vtsi::StreamCallLogsResponse>* StreamCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request) override;
    ::grpc::ClientAsyncReader< ::ondewo::vtsi::StreamCallLogsResponse>* AsyncStreamCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::ondewo::vtsi::StreamCallLogsResponse>* PrepareAsyncStreamCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::StreamCallLogsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogsResponse>* AsyncListCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogsResponse>* PrepareAsyncListCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::CallLogStream>* AsyncGetCallLogStreamRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::CallLogStream>* PrepareAsyncGetCallLogStreamRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogStreamsResponse>* AsyncListCallLogStreamsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListCallLogStreamsResponse>* PrepareAsyncListCallLogStreamsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::DeleteCallLogsResponse>* AsyncDeleteCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::DeleteCallLogsResponse>* PrepareAsyncDeleteCallLogsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamCallLogs_;
    const ::grpc::internal::RpcMethod rpcmethod_ListCallLogs_;
    const ::grpc::internal::RpcMethod rpcmethod_GetCallLogStream_;
    const ::grpc::internal::RpcMethod rpcmethod_ListCallLogStreams_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteCallLogs_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // ////////////////////////////////////////////////////////////////////////////
    // Call log endpoints
    // ////////////////////////////////////////////////////////////////////////////
    //
    // <p>Streams the container logs of the ondewo-sip / ondewo-csi containers of a VTSI project as
    // they are captured, in the manner of <code>docker logs --follow</code>. The stream replays
    // <code>tail_lines</code> historical entries and then follows. It stays open until the capture
    // of every matching log stream has terminated, until the client disconnects, or until the
    // server-side maximum stream duration is reached.</p>
    // <p>Entries are served from the VTSI database rather than from the docker daemon, so a
    // container that has already been removed still streams. Secrets are redacted server-side.</p>
    virtual ::grpc::Status StreamCallLogs(::grpc::ServerContext* context, const ::ondewo::vtsi::StreamCallLogsRequest* request, ::grpc::ServerWriter< ::ondewo::vtsi::StreamCallLogsResponse>* writer);
    // <p>Returns a bounded, filtered page of captured container log entries. Supports a time window,
    // severity filtering, a regular expression, a plain-text search and cursor paging in both
    // directions for infinite scrolling. Secrets are redacted server-side.</p>
    virtual ::grpc::Status ListCallLogs(::grpc::ServerContext* context, const ::ondewo::vtsi::ListCallLogsRequest* request, ::ondewo::vtsi::ListCallLogsResponse* response);
    // <p>Returns the capture state of a single log stream, i.e. of one capture generation of one
    // container.</p>
    virtual ::grpc::Status GetCallLogStream(::grpc::ServerContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest* request, ::ondewo::vtsi::CallLogStream* response);
    // <p>Lists the log streams VTSI has captured for a project. A single container yields a new log
    // stream every time it is recreated, because a recreated container is a new docker container
    // whose previous logs no longer exist.</p>
    virtual ::grpc::Status ListCallLogStreams(::grpc::ServerContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest* request, ::ondewo::vtsi::ListCallLogStreamsResponse* response);
    // <p>Permanently deletes captured log entries matching a filter. This is the erasure path for
    // data-subject requests: retention answers &quot;delete everything older than N days&quot;, this
    // answers &quot;delete everything for this call or this phone number&quot;.</p>
    virtual ::grpc::Status DeleteCallLogs(::grpc::ServerContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest* request, ::ondewo::vtsi::DeleteCallLogsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamCallLogs() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::StreamCallLogsRequest* /*request*/, ::grpc::ServerWriter< ::ondewo::vtsi::StreamCallLogsResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamCallLogs(::grpc::ServerContext* context, ::ondewo::vtsi::StreamCallLogsRequest* request, ::grpc::ServerAsyncWriter< ::ondewo::vtsi::StreamCallLogsResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListCallLogs() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogsRequest* /*request*/, ::ondewo::vtsi::ListCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListCallLogs(::grpc::ServerContext* context, ::ondewo::vtsi::ListCallLogsRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::vtsi::ListCallLogsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCallLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetCallLogStream() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetCallLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCallLogStream(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::GetCallLogStreamRequest* /*request*/, ::ondewo::vtsi::CallLogStream* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCallLogStream(::grpc::ServerContext* context, ::ondewo::vtsi::GetCallLogStreamRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::vtsi::CallLogStream>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListCallLogStreams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListCallLogStreams() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ListCallLogStreams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCallLogStreams(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogStreamsRequest* /*request*/, ::ondewo::vtsi::ListCallLogStreamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListCallLogStreams(::grpc::ServerContext* context, ::ondewo::vtsi::ListCallLogStreamsRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::vtsi::ListCallLogStreamsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteCallLogs() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DeleteCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::DeleteCallLogsRequest* /*request*/, ::ondewo::vtsi::DeleteCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteCallLogs(::grpc::ServerContext* context, ::ondewo::vtsi::DeleteCallLogsRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::vtsi::DeleteCallLogsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamCallLogs<WithAsyncMethod_ListCallLogs<WithAsyncMethod_GetCallLogStream<WithAsyncMethod_ListCallLogStreams<WithAsyncMethod_DeleteCallLogs<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamCallLogs() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::ondewo::vtsi::StreamCallLogsRequest, ::ondewo::vtsi::StreamCallLogsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::vtsi::StreamCallLogsRequest* request) { return this->StreamCallLogs(context, request); }));
    }
    ~WithCallbackMethod_StreamCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::StreamCallLogsRequest* /*request*/, ::grpc::ServerWriter< ::ondewo::vtsi::StreamCallLogsResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::ondewo::vtsi::StreamCallLogsResponse>* StreamCallLogs(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::vtsi::StreamCallLogsRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListCallLogs() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::vtsi::ListCallLogsRequest, ::ondewo::vtsi::ListCallLogsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::vtsi::ListCallLogsRequest* request, ::ondewo::vtsi::ListCallLogsResponse* response) { return this->ListCallLogs(context, request, response); }));}
    void SetMessageAllocatorFor_ListCallLogs(
        ::grpc::MessageAllocator< ::ondewo::vtsi::ListCallLogsRequest, ::ondewo::vtsi::ListCallLogsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::vtsi::ListCallLogsRequest, ::ondewo::vtsi::ListCallLogsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogsRequest* /*request*/, ::ondewo::vtsi::ListCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListCallLogs(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogsRequest* /*request*/, ::ondewo::vtsi::ListCallLogsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetCallLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetCallLogStream() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::vtsi::GetCallLogStreamRequest, ::ondewo::vtsi::CallLogStream>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::vtsi::GetCallLogStreamRequest* request, ::ondewo::vtsi::CallLogStream* response) { return this->GetCallLogStream(context, request, response); }));}
    void SetMessageAllocatorFor_GetCallLogStream(
        ::grpc::MessageAllocator< ::ondewo::vtsi::GetCallLogStreamRequest, ::ondewo::vtsi::CallLogStream>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::vtsi::GetCallLogStreamRequest, ::ondewo::vtsi::CallLogStream>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetCallLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCallLogStream(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::GetCallLogStreamRequest* /*request*/, ::ondewo::vtsi::CallLogStream* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCallLogStream(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::vtsi::GetCallLogStreamRequest* /*request*/, ::ondewo::vtsi::CallLogStream* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListCallLogStreams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListCallLogStreams() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::vtsi::ListCallLogStreamsRequest, ::ondewo::vtsi::ListCallLogStreamsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::vtsi::ListCallLogStreamsRequest* request, ::ondewo::vtsi::ListCallLogStreamsResponse* response) { return this->ListCallLogStreams(context, request, response); }));}
    void SetMessageAllocatorFor_ListCallLogStreams(
        ::grpc::MessageAllocator< ::ondewo::vtsi::ListCallLogStreamsRequest, ::ondewo::vtsi::ListCallLogStreamsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::vtsi::ListCallLogStreamsRequest, ::ondewo::vtsi::ListCallLogStreamsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListCallLogStreams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCallLogStreams(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogStreamsRequest* /*request*/, ::ondewo::vtsi::ListCallLogStreamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListCallLogStreams(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogStreamsRequest* /*request*/, ::ondewo::vtsi::ListCallLogStreamsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteCallLogs() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::vtsi::DeleteCallLogsRequest, ::ondewo::vtsi::DeleteCallLogsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::vtsi::DeleteCallLogsRequest* request, ::ondewo::vtsi::DeleteCallLogsResponse* response) { return this->DeleteCallLogs(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteCallLogs(
        ::grpc::MessageAllocator< ::ondewo::vtsi::DeleteCallLogsRequest, ::ondewo::vtsi::DeleteCallLogsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::vtsi::DeleteCallLogsRequest, ::ondewo::vtsi::DeleteCallLogsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::DeleteCallLogsRequest* /*request*/, ::ondewo::vtsi::DeleteCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteCallLogs(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::vtsi::DeleteCallLogsRequest* /*request*/, ::ondewo::vtsi::DeleteCallLogsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamCallLogs<WithCallbackMethod_ListCallLogs<WithCallbackMethod_GetCallLogStream<WithCallbackMethod_ListCallLogStreams<WithCallbackMethod_DeleteCallLogs<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamCallLogs() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::StreamCallLogsRequest* /*request*/, ::grpc::ServerWriter< ::ondewo::vtsi::StreamCallLogsResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListCallLogs() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogsRequest* /*request*/, ::ondewo::vtsi::ListCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetCallLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetCallLogStream() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetCallLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCallLogStream(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::GetCallLogStreamRequest* /*request*/, ::ondewo::vtsi::CallLogStream* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListCallLogStreams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListCallLogStreams() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ListCallLogStreams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCallLogStreams(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogStreamsRequest* /*request*/, ::ondewo::vtsi::ListCallLogStreamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteCallLogs() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DeleteCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::DeleteCallLogsRequest* /*request*/, ::ondewo::vtsi::DeleteCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamCallLogs() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::StreamCallLogsRequest* /*request*/, ::grpc::ServerWriter< ::ondewo::vtsi::StreamCallLogsResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamCallLogs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListCallLogs() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogsRequest* /*request*/, ::ondewo::vtsi::ListCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListCallLogs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCallLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetCallLogStream() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetCallLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCallLogStream(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::GetCallLogStreamRequest* /*request*/, ::ondewo::vtsi::CallLogStream* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCallLogStream(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListCallLogStreams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListCallLogStreams() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ListCallLogStreams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCallLogStreams(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogStreamsRequest* /*request*/, ::ondewo::vtsi::ListCallLogStreamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListCallLogStreams(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteCallLogs() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_DeleteCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::DeleteCallLogsRequest* /*request*/, ::ondewo::vtsi::DeleteCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteCallLogs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamCallLogs() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamCallLogs(context, request); }));
    }
    ~WithRawCallbackMethod_StreamCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::StreamCallLogsRequest* /*request*/, ::grpc::ServerWriter< ::ondewo::vtsi::StreamCallLogsResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamCallLogs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListCallLogs() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListCallLogs(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogsRequest* /*request*/, ::ondewo::vtsi::ListCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListCallLogs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetCallLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetCallLogStream() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetCallLogStream(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetCallLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCallLogStream(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::GetCallLogStreamRequest* /*request*/, ::ondewo::vtsi::CallLogStream* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetCallLogStream(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListCallLogStreams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListCallLogStreams() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListCallLogStreams(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListCallLogStreams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListCallLogStreams(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogStreamsRequest* /*request*/, ::ondewo::vtsi::ListCallLogStreamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListCallLogStreams(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteCallLogs() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteCallLogs(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::DeleteCallLogsRequest* /*request*/, ::ondewo::vtsi::DeleteCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteCallLogs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListCallLogs() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::vtsi::ListCallLogsRequest, ::ondewo::vtsi::ListCallLogsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::vtsi::ListCallLogsRequest, ::ondewo::vtsi::ListCallLogsResponse>* streamer) {
                       return this->StreamedListCallLogs(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogsRequest* /*request*/, ::ondewo::vtsi::ListCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListCallLogs(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::vtsi::ListCallLogsRequest,::ondewo::vtsi::ListCallLogsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCallLogStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetCallLogStream() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::vtsi::GetCallLogStreamRequest, ::ondewo::vtsi::CallLogStream>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::vtsi::GetCallLogStreamRequest, ::ondewo::vtsi::CallLogStream>* streamer) {
                       return this->StreamedGetCallLogStream(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetCallLogStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCallLogStream(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::GetCallLogStreamRequest* /*request*/, ::ondewo::vtsi::CallLogStream* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCallLogStream(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::vtsi::GetCallLogStreamRequest,::ondewo::vtsi::CallLogStream>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListCallLogStreams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListCallLogStreams() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::vtsi::ListCallLogStreamsRequest, ::ondewo::vtsi::ListCallLogStreamsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::vtsi::ListCallLogStreamsRequest, ::ondewo::vtsi::ListCallLogStreamsResponse>* streamer) {
                       return this->StreamedListCallLogStreams(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListCallLogStreams() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListCallLogStreams(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::ListCallLogStreamsRequest* /*request*/, ::ondewo::vtsi::ListCallLogStreamsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListCallLogStreams(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::vtsi::ListCallLogStreamsRequest,::ondewo::vtsi::ListCallLogStreamsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteCallLogs() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::vtsi::DeleteCallLogsRequest, ::ondewo::vtsi::DeleteCallLogsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::vtsi::DeleteCallLogsRequest, ::ondewo::vtsi::DeleteCallLogsResponse>* streamer) {
                       return this->StreamedDeleteCallLogs(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::DeleteCallLogsRequest* /*request*/, ::ondewo::vtsi::DeleteCallLogsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteCallLogs(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::vtsi::DeleteCallLogsRequest,::ondewo::vtsi::DeleteCallLogsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListCallLogs<WithStreamedUnaryMethod_GetCallLogStream<WithStreamedUnaryMethod_ListCallLogStreams<WithStreamedUnaryMethod_DeleteCallLogs<Service > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamCallLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamCallLogs() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::ondewo::vtsi::StreamCallLogsRequest, ::ondewo::vtsi::StreamCallLogsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::ondewo::vtsi::StreamCallLogsRequest, ::ondewo::vtsi::StreamCallLogsResponse>* streamer) {
                       return this->StreamedStreamCallLogs(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamCallLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamCallLogs(::grpc::ServerContext* /*context*/, const ::ondewo::vtsi::StreamCallLogsRequest* /*request*/, ::grpc::ServerWriter< ::ondewo::vtsi::StreamCallLogsResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamCallLogs(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::ondewo::vtsi::StreamCallLogsRequest,::ondewo::vtsi::StreamCallLogsResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamCallLogs<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_StreamCallLogs<WithStreamedUnaryMethod_ListCallLogs<WithStreamedUnaryMethod_GetCallLogStream<WithStreamedUnaryMethod_ListCallLogStreams<WithStreamedUnaryMethod_DeleteCallLogs<Service > > > > > StreamedService;
};

}  // namespace vtsi
}  // namespace ondewo


#endif  // GRPC_ondewo_2fvtsi_2flogs_2eproto__INCLUDED
