// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ondewo/vtsi/softphones.proto

#include "ondewo/vtsi/softphones.pb.h"
#include "ondewo/vtsi/softphones.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ondewo {
namespace vtsi {

static const char* Softphones_method_names[] = {
  "/ondewo.vtsi.Softphones/CreateSoftphoneAccount",
  "/ondewo.vtsi.Softphones/GetSoftphoneAccount",
  "/ondewo.vtsi.Softphones/UpdateSoftphoneAccount",
  "/ondewo.vtsi.Softphones/DeleteSoftphoneAccount",
  "/ondewo.vtsi.Softphones/ListSoftphoneAccounts",
  "/ondewo.vtsi.Softphones/RotateSoftphoneCredentials",
  "/ondewo.vtsi.Softphones/ListSoftphoneCertificates",
  "/ondewo.vtsi.Softphones/GetSoftphoneCertificate",
  "/ondewo.vtsi.Softphones/RevokeSoftphoneCertificate",
  "/ondewo.vtsi.Softphones/GetSoftphoneProvisioning",
};

std::unique_ptr< Softphones::Stub> Softphones::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Softphones::Stub> stub(new Softphones::Stub(channel, options));
  return stub;
}

Softphones::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateSoftphoneAccount_(Softphones_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSoftphoneAccount_(Softphones_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateSoftphoneAccount_(Softphones_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteSoftphoneAccount_(Softphones_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListSoftphoneAccounts_(Softphones_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RotateSoftphoneCredentials_(Softphones_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListSoftphoneCertificates_(Softphones_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSoftphoneCertificate_(Softphones_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RevokeSoftphoneCertificate_(Softphones_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSoftphoneProvisioning_(Softphones_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Softphones::Stub::CreateSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::CreateSoftphoneAccountRequest& request, ::ondewo::vtsi::CreateSoftphoneAccountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::vtsi::CreateSoftphoneAccountRequest, ::ondewo::vtsi::CreateSoftphoneAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateSoftphoneAccount_, context, request, response);
}

void Softphones::Stub::async::CreateSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::CreateSoftphoneAccountRequest* request, ::ondewo::vtsi::CreateSoftphoneAccountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::vtsi::CreateSoftphoneAccountRequest, ::ondewo::vtsi::CreateSoftphoneAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateSoftphoneAccount_, context, request, response, std::move(f));
}

void Softphones::Stub::async::CreateSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::CreateSoftphoneAccountRequest* request, ::ondewo::vtsi::CreateSoftphoneAccountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateSoftphoneAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::CreateSoftphoneAccountResponse>* Softphones::Stub::PrepareAsyncCreateSoftphoneAccountRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::CreateSoftphoneAccountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::vtsi::CreateSoftphoneAccountResponse, ::ondewo::vtsi::CreateSoftphoneAccountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateSoftphoneAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::CreateSoftphoneAccountResponse>* Softphones::Stub::AsyncCreateSoftphoneAccountRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::CreateSoftphoneAccountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateSoftphoneAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Softphones::Stub::GetSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneAccountRequest& request, ::ondewo::vtsi::SoftphoneAccount* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::vtsi::GetSoftphoneAccountRequest, ::ondewo::vtsi::SoftphoneAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSoftphoneAccount_, context, request, response);
}

void Softphones::Stub::async::GetSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneAccountRequest* request, ::ondewo::vtsi::SoftphoneAccount* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::vtsi::GetSoftphoneAccountRequest, ::ondewo::vtsi::SoftphoneAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSoftphoneAccount_, context, request, response, std::move(f));
}

void Softphones::Stub::async::GetSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneAccountRequest* request, ::ondewo::vtsi::SoftphoneAccount* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSoftphoneAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::SoftphoneAccount>* Softphones::Stub::PrepareAsyncGetSoftphoneAccountRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneAccountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::vtsi::SoftphoneAccount, ::ondewo::vtsi::GetSoftphoneAccountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSoftphoneAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::SoftphoneAccount>* Softphones::Stub::AsyncGetSoftphoneAccountRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneAccountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSoftphoneAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Softphones::Stub::UpdateSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::UpdateSoftphoneAccountRequest& request, ::ondewo::vtsi::SoftphoneAccount* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::vtsi::UpdateSoftphoneAccountRequest, ::ondewo::vtsi::SoftphoneAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateSoftphoneAccount_, context, request, response);
}

void Softphones::Stub::async::UpdateSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::UpdateSoftphoneAccountRequest* request, ::ondewo::vtsi::SoftphoneAccount* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::vtsi::UpdateSoftphoneAccountRequest, ::ondewo::vtsi::SoftphoneAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateSoftphoneAccount_, context, request, response, std::move(f));
}

void Softphones::Stub::async::UpdateSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::UpdateSoftphoneAccountRequest* request, ::ondewo::vtsi::SoftphoneAccount* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateSoftphoneAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::SoftphoneAccount>* Softphones::Stub::PrepareAsyncUpdateSoftphoneAccountRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::UpdateSoftphoneAccountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::vtsi::SoftphoneAccount, ::ondewo::vtsi::UpdateSoftphoneAccountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateSoftphoneAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::SoftphoneAccount>* Softphones::Stub::AsyncUpdateSoftphoneAccountRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::UpdateSoftphoneAccountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateSoftphoneAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Softphones::Stub::DeleteSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteSoftphoneAccountRequest& request, ::ondewo::vtsi::DeleteSoftphoneAccountResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::vtsi::DeleteSoftphoneAccountRequest, ::ondewo::vtsi::DeleteSoftphoneAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteSoftphoneAccount_, context, request, response);
}

void Softphones::Stub::async::DeleteSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteSoftphoneAccountRequest* request, ::ondewo::vtsi::DeleteSoftphoneAccountResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::vtsi::DeleteSoftphoneAccountRequest, ::ondewo::vtsi::DeleteSoftphoneAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteSoftphoneAccount_, context, request, response, std::move(f));
}

void Softphones::Stub::async::DeleteSoftphoneAccount(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteSoftphoneAccountRequest* request, ::ondewo::vtsi::DeleteSoftphoneAccountResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteSoftphoneAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::DeleteSoftphoneAccountResponse>* Softphones::Stub::PrepareAsyncDeleteSoftphoneAccountRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteSoftphoneAccountRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::vtsi::DeleteSoftphoneAccountResponse, ::ondewo::vtsi::DeleteSoftphoneAccountRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteSoftphoneAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::DeleteSoftphoneAccountResponse>* Softphones::Stub::AsyncDeleteSoftphoneAccountRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::DeleteSoftphoneAccountRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteSoftphoneAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Softphones::Stub::ListSoftphoneAccounts(::grpc::ClientContext* context, const ::ondewo::vtsi::ListSoftphoneAccountsRequest& request, ::ondewo::vtsi::ListSoftphoneAccountsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::vtsi::ListSoftphoneAccountsRequest, ::ondewo::vtsi::ListSoftphoneAccountsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListSoftphoneAccounts_, context, request, response);
}

void Softphones::Stub::async::ListSoftphoneAccounts(::grpc::ClientContext* context, const ::ondewo::vtsi::ListSoftphoneAccountsRequest* request, ::ondewo::vtsi::ListSoftphoneAccountsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::vtsi::ListSoftphoneAccountsRequest, ::ondewo::vtsi::ListSoftphoneAccountsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSoftphoneAccounts_, context, request, response, std::move(f));
}

void Softphones::Stub::async::ListSoftphoneAccounts(::grpc::ClientContext* context, const ::ondewo::vtsi::ListSoftphoneAccountsRequest* request, ::ondewo::vtsi::ListSoftphoneAccountsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSoftphoneAccounts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListSoftphoneAccountsResponse>* Softphones::Stub::PrepareAsyncListSoftphoneAccountsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListSoftphoneAccountsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::vtsi::ListSoftphoneAccountsResponse, ::ondewo::vtsi::ListSoftphoneAccountsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListSoftphoneAccounts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListSoftphoneAccountsResponse>* Softphones::Stub::AsyncListSoftphoneAccountsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListSoftphoneAccountsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListSoftphoneAccountsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Softphones::Stub::RotateSoftphoneCredentials(::grpc::ClientContext* context, const ::ondewo::vtsi::RotateSoftphoneCredentialsRequest& request, ::ondewo::vtsi::RotateSoftphoneCredentialsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::vtsi::RotateSoftphoneCredentialsRequest, ::ondewo::vtsi::RotateSoftphoneCredentialsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RotateSoftphoneCredentials_, context, request, response);
}

void Softphones::Stub::async::RotateSoftphoneCredentials(::grpc::ClientContext* context, const ::ondewo::vtsi::RotateSoftphoneCredentialsRequest* request, ::ondewo::vtsi::RotateSoftphoneCredentialsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::vtsi::RotateSoftphoneCredentialsRequest, ::ondewo::vtsi::RotateSoftphoneCredentialsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RotateSoftphoneCredentials_, context, request, response, std::move(f));
}

void Softphones::Stub::async::RotateSoftphoneCredentials(::grpc::ClientContext* context, const ::ondewo::vtsi::RotateSoftphoneCredentialsRequest* request, ::ondewo::vtsi::RotateSoftphoneCredentialsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RotateSoftphoneCredentials_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::RotateSoftphoneCredentialsResponse>* Softphones::Stub::PrepareAsyncRotateSoftphoneCredentialsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::RotateSoftphoneCredentialsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::vtsi::RotateSoftphoneCredentialsResponse, ::ondewo::vtsi::RotateSoftphoneCredentialsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RotateSoftphoneCredentials_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::RotateSoftphoneCredentialsResponse>* Softphones::Stub::AsyncRotateSoftphoneCredentialsRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::RotateSoftphoneCredentialsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRotateSoftphoneCredentialsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Softphones::Stub::ListSoftphoneCertificates(::grpc::ClientContext* context, const ::ondewo::vtsi::ListSoftphoneCertificatesRequest& request, ::ondewo::vtsi::ListSoftphoneCertificatesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::vtsi::ListSoftphoneCertificatesRequest, ::ondewo::vtsi::ListSoftphoneCertificatesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListSoftphoneCertificates_, context, request, response);
}

void Softphones::Stub::async::ListSoftphoneCertificates(::grpc::ClientContext* context, const ::ondewo::vtsi::ListSoftphoneCertificatesRequest* request, ::ondewo::vtsi::ListSoftphoneCertificatesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::vtsi::ListSoftphoneCertificatesRequest, ::ondewo::vtsi::ListSoftphoneCertificatesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSoftphoneCertificates_, context, request, response, std::move(f));
}

void Softphones::Stub::async::ListSoftphoneCertificates(::grpc::ClientContext* context, const ::ondewo::vtsi::ListSoftphoneCertificatesRequest* request, ::ondewo::vtsi::ListSoftphoneCertificatesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSoftphoneCertificates_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListSoftphoneCertificatesResponse>* Softphones::Stub::PrepareAsyncListSoftphoneCertificatesRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListSoftphoneCertificatesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::vtsi::ListSoftphoneCertificatesResponse, ::ondewo::vtsi::ListSoftphoneCertificatesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListSoftphoneCertificates_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::ListSoftphoneCertificatesResponse>* Softphones::Stub::AsyncListSoftphoneCertificatesRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::ListSoftphoneCertificatesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListSoftphoneCertificatesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Softphones::Stub::GetSoftphoneCertificate(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneCertificateRequest& request, ::ondewo::vtsi::SoftphoneCertificate* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::vtsi::GetSoftphoneCertificateRequest, ::ondewo::vtsi::SoftphoneCertificate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSoftphoneCertificate_, context, request, response);
}

void Softphones::Stub::async::GetSoftphoneCertificate(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneCertificateRequest* request, ::ondewo::vtsi::SoftphoneCertificate* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::vtsi::GetSoftphoneCertificateRequest, ::ondewo::vtsi::SoftphoneCertificate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSoftphoneCertificate_, context, request, response, std::move(f));
}

void Softphones::Stub::async::GetSoftphoneCertificate(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneCertificateRequest* request, ::ondewo::vtsi::SoftphoneCertificate* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSoftphoneCertificate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::SoftphoneCertificate>* Softphones::Stub::PrepareAsyncGetSoftphoneCertificateRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneCertificateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::vtsi::SoftphoneCertificate, ::ondewo::vtsi::GetSoftphoneCertificateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSoftphoneCertificate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::SoftphoneCertificate>* Softphones::Stub::AsyncGetSoftphoneCertificateRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneCertificateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSoftphoneCertificateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Softphones::Stub::RevokeSoftphoneCertificate(::grpc::ClientContext* context, const ::ondewo::vtsi::RevokeSoftphoneCertificateRequest& request, ::ondewo::vtsi::SoftphoneCertificate* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::vtsi::RevokeSoftphoneCertificateRequest, ::ondewo::vtsi::SoftphoneCertificate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RevokeSoftphoneCertificate_, context, request, response);
}

void Softphones::Stub::async::RevokeSoftphoneCertificate(::grpc::ClientContext* context, const ::ondewo::vtsi::RevokeSoftphoneCertificateRequest* request, ::ondewo::vtsi::SoftphoneCertificate* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::vtsi::RevokeSoftphoneCertificateRequest, ::ondewo::vtsi::SoftphoneCertificate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RevokeSoftphoneCertificate_, context, request, response, std::move(f));
}

void Softphones::Stub::async::RevokeSoftphoneCertificate(::grpc::ClientContext* context, const ::ondewo::vtsi::RevokeSoftphoneCertificateRequest* request, ::ondewo::vtsi::SoftphoneCertificate* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RevokeSoftphoneCertificate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::SoftphoneCertificate>* Softphones::Stub::PrepareAsyncRevokeSoftphoneCertificateRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::RevokeSoftphoneCertificateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::vtsi::SoftphoneCertificate, ::ondewo::vtsi::RevokeSoftphoneCertificateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RevokeSoftphoneCertificate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::SoftphoneCertificate>* Softphones::Stub::AsyncRevokeSoftphoneCertificateRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::RevokeSoftphoneCertificateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRevokeSoftphoneCertificateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Softphones::Stub::GetSoftphoneProvisioning(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneProvisioningRequest& request, ::ondewo::vtsi::SoftphoneProvisioning* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::vtsi::GetSoftphoneProvisioningRequest, ::ondewo::vtsi::SoftphoneProvisioning, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSoftphoneProvisioning_, context, request, response);
}

void Softphones::Stub::async::GetSoftphoneProvisioning(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneProvisioningRequest* request, ::ondewo::vtsi::SoftphoneProvisioning* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::vtsi::GetSoftphoneProvisioningRequest, ::ondewo::vtsi::SoftphoneProvisioning, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSoftphoneProvisioning_, context, request, response, std::move(f));
}

void Softphones::Stub::async::GetSoftphoneProvisioning(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneProvisioningRequest* request, ::ondewo::vtsi::SoftphoneProvisioning* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSoftphoneProvisioning_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::SoftphoneProvisioning>* Softphones::Stub::PrepareAsyncGetSoftphoneProvisioningRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneProvisioningRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::vtsi::SoftphoneProvisioning, ::ondewo::vtsi::GetSoftphoneProvisioningRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSoftphoneProvisioning_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::vtsi::SoftphoneProvisioning>* Softphones::Stub::AsyncGetSoftphoneProvisioningRaw(::grpc::ClientContext* context, const ::ondewo::vtsi::GetSoftphoneProvisioningRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSoftphoneProvisioningRaw(context, request, cq);
  result->StartCall();
  return result;
}

Softphones::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Softphones_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Softphones::Service, ::ondewo::vtsi::CreateSoftphoneAccountRequest, ::ondewo::vtsi::CreateSoftphoneAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Softphones::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::vtsi::CreateSoftphoneAccountRequest* req,
             ::ondewo::vtsi::CreateSoftphoneAccountResponse* resp) {
               return service->CreateSoftphoneAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Softphones_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Softphones::Service, ::ondewo::vtsi::GetSoftphoneAccountRequest, ::ondewo::vtsi::SoftphoneAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Softphones::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::vtsi::GetSoftphoneAccountRequest* req,
             ::ondewo::vtsi::SoftphoneAccount* resp) {
               return service->GetSoftphoneAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Softphones_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Softphones::Service, ::ondewo::vtsi::UpdateSoftphoneAccountRequest, ::ondewo::vtsi::SoftphoneAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Softphones::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::vtsi::UpdateSoftphoneAccountRequest* req,
             ::ondewo::vtsi::SoftphoneAccount* resp) {
               return service->UpdateSoftphoneAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Softphones_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Softphones::Service, ::ondewo::vtsi::DeleteSoftphoneAccountRequest, ::ondewo::vtsi::DeleteSoftphoneAccountResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Softphones::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::vtsi::DeleteSoftphoneAccountRequest* req,
             ::ondewo::vtsi::DeleteSoftphoneAccountResponse* resp) {
               return service->DeleteSoftphoneAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Softphones_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Softphones::Service, ::ondewo::vtsi::ListSoftphoneAccountsRequest, ::ondewo::vtsi::ListSoftphoneAccountsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Softphones::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::vtsi::ListSoftphoneAccountsRequest* req,
             ::ondewo::vtsi::ListSoftphoneAccountsResponse* resp) {
               return service->ListSoftphoneAccounts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Softphones_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Softphones::Service, ::ondewo::vtsi::RotateSoftphoneCredentialsRequest, ::ondewo::vtsi::RotateSoftphoneCredentialsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Softphones::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::vtsi::RotateSoftphoneCredentialsRequest* req,
             ::ondewo::vtsi::RotateSoftphoneCredentialsResponse* resp) {
               return service->RotateSoftphoneCredentials(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Softphones_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Softphones::Service, ::ondewo::vtsi::ListSoftphoneCertificatesRequest, ::ondewo::vtsi::ListSoftphoneCertificatesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Softphones::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::vtsi::ListSoftphoneCertificatesRequest* req,
             ::ondewo::vtsi::ListSoftphoneCertificatesResponse* resp) {
               return service->ListSoftphoneCertificates(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Softphones_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Softphones::Service, ::ondewo::vtsi::GetSoftphoneCertificateRequest, ::ondewo::vtsi::SoftphoneCertificate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Softphones::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::vtsi::GetSoftphoneCertificateRequest* req,
             ::ondewo::vtsi::SoftphoneCertificate* resp) {
               return service->GetSoftphoneCertificate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Softphones_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Softphones::Service, ::ondewo::vtsi::RevokeSoftphoneCertificateRequest, ::ondewo::vtsi::SoftphoneCertificate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Softphones::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::vtsi::RevokeSoftphoneCertificateRequest* req,
             ::ondewo::vtsi::SoftphoneCertificate* resp) {
               return service->RevokeSoftphoneCertificate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Softphones_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Softphones::Service, ::ondewo::vtsi::GetSoftphoneProvisioningRequest, ::ondewo::vtsi::SoftphoneProvisioning, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Softphones::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::vtsi::GetSoftphoneProvisioningRequest* req,
             ::ondewo::vtsi::SoftphoneProvisioning* resp) {
               return service->GetSoftphoneProvisioning(ctx, req, resp);
             }, this)));
}

Softphones::Service::~Service() {
}

::grpc::Status Softphones::Service::CreateSoftphoneAccount(::grpc::ServerContext* context, const ::ondewo::vtsi::CreateSoftphoneAccountRequest* request, ::ondewo::vtsi::CreateSoftphoneAccountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Softphones::Service::GetSoftphoneAccount(::grpc::ServerContext* context, const ::ondewo::vtsi::GetSoftphoneAccountRequest* request, ::ondewo::vtsi::SoftphoneAccount* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Softphones::Service::UpdateSoftphoneAccount(::grpc::ServerContext* context, const ::ondewo::vtsi::UpdateSoftphoneAccountRequest* request, ::ondewo::vtsi::SoftphoneAccount* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Softphones::Service::DeleteSoftphoneAccount(::grpc::ServerContext* context, const ::ondewo::vtsi::DeleteSoftphoneAccountRequest* request, ::ondewo::vtsi::DeleteSoftphoneAccountResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Softphones::Service::ListSoftphoneAccounts(::grpc::ServerContext* context, const ::ondewo::vtsi::ListSoftphoneAccountsRequest* request, ::ondewo::vtsi::ListSoftphoneAccountsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Softphones::Service::RotateSoftphoneCredentials(::grpc::ServerContext* context, const ::ondewo::vtsi::RotateSoftphoneCredentialsRequest* request, ::ondewo::vtsi::RotateSoftphoneCredentialsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Softphones::Service::ListSoftphoneCertificates(::grpc::ServerContext* context, const ::ondewo::vtsi::ListSoftphoneCertificatesRequest* request, ::ondewo::vtsi::ListSoftphoneCertificatesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Softphones::Service::GetSoftphoneCertificate(::grpc::ServerContext* context, const ::ondewo::vtsi::GetSoftphoneCertificateRequest* request, ::ondewo::vtsi::SoftphoneCertificate* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Softphones::Service::RevokeSoftphoneCertificate(::grpc::ServerContext* context, const ::ondewo::vtsi::RevokeSoftphoneCertificateRequest* request, ::ondewo::vtsi::SoftphoneCertificate* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Softphones::Service::GetSoftphoneProvisioning(::grpc::ServerContext* context, const ::ondewo::vtsi::GetSoftphoneProvisioningRequest* request, ::ondewo::vtsi::SoftphoneProvisioning* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ondewo
}  // namespace vtsi

