// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ondewo/nlu/aiservices.proto

#include "ondewo/nlu/aiservices.pb.h"
#include "ondewo/nlu/aiservices.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ondewo {
namespace nlu {

static const char* AiServices_method_names[] = {
  "/ondewo.nlu.AiServices/ExtractEntities",
  "/ondewo.nlu.AiServices/GenerateUserSays",
  "/ondewo.nlu.AiServices/GenerateResponses",
  "/ondewo.nlu.AiServices/GetAlternativeSentences",
  "/ondewo.nlu.AiServices/GetAlternativeTrainingPhrases",
  "/ondewo.nlu.AiServices/GetSynonyms",
  "/ondewo.nlu.AiServices/ClassifyIntents",
  "/ondewo.nlu.AiServices/ExtractEntitiesFuzzy",
  "/ondewo.nlu.AiServices/LlmGenerate",
  "/ondewo.nlu.AiServices/StreamingLlmGenerate",
  "/ondewo.nlu.AiServices/ListLlmModels",
};

std::unique_ptr< AiServices::Stub> AiServices::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AiServices::Stub> stub(new AiServices::Stub(channel, options));
  return stub;
}

AiServices::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExtractEntities_(AiServices_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GenerateUserSays_(AiServices_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GenerateResponses_(AiServices_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAlternativeSentences_(AiServices_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAlternativeTrainingPhrases_(AiServices_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSynonyms_(AiServices_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ClassifyIntents_(AiServices_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ExtractEntitiesFuzzy_(AiServices_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LlmGenerate_(AiServices_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamingLlmGenerate_(AiServices_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ListLlmModels_(AiServices_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AiServices::Stub::ExtractEntities(::grpc::ClientContext* context, const ::ondewo::nlu::ExtractEntitiesRequest& request, ::ondewo::nlu::ExtractEntitiesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::ExtractEntitiesRequest, ::ondewo::nlu::ExtractEntitiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExtractEntities_, context, request, response);
}

void AiServices::Stub::async::ExtractEntities(::grpc::ClientContext* context, const ::ondewo::nlu::ExtractEntitiesRequest* request, ::ondewo::nlu::ExtractEntitiesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::ExtractEntitiesRequest, ::ondewo::nlu::ExtractEntitiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExtractEntities_, context, request, response, std::move(f));
}

void AiServices::Stub::async::ExtractEntities(::grpc::ClientContext* context, const ::ondewo::nlu::ExtractEntitiesRequest* request, ::ondewo::nlu::ExtractEntitiesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExtractEntities_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ExtractEntitiesResponse>* AiServices::Stub::PrepareAsyncExtractEntitiesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ExtractEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::ExtractEntitiesResponse, ::ondewo::nlu::ExtractEntitiesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExtractEntities_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ExtractEntitiesResponse>* AiServices::Stub::AsyncExtractEntitiesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ExtractEntitiesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExtractEntitiesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AiServices::Stub::GenerateUserSays(::grpc::ClientContext* context, const ::ondewo::nlu::GenerateUserSaysRequest& request, ::ondewo::nlu::GenerateUserSaysResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::GenerateUserSaysRequest, ::ondewo::nlu::GenerateUserSaysResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GenerateUserSays_, context, request, response);
}

void AiServices::Stub::async::GenerateUserSays(::grpc::ClientContext* context, const ::ondewo::nlu::GenerateUserSaysRequest* request, ::ondewo::nlu::GenerateUserSaysResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::GenerateUserSaysRequest, ::ondewo::nlu::GenerateUserSaysResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GenerateUserSays_, context, request, response, std::move(f));
}

void AiServices::Stub::async::GenerateUserSays(::grpc::ClientContext* context, const ::ondewo::nlu::GenerateUserSaysRequest* request, ::ondewo::nlu::GenerateUserSaysResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GenerateUserSays_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::GenerateUserSaysResponse>* AiServices::Stub::PrepareAsyncGenerateUserSaysRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GenerateUserSaysRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::GenerateUserSaysResponse, ::ondewo::nlu::GenerateUserSaysRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GenerateUserSays_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::GenerateUserSaysResponse>* AiServices::Stub::AsyncGenerateUserSaysRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GenerateUserSaysRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGenerateUserSaysRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AiServices::Stub::GenerateResponses(::grpc::ClientContext* context, const ::ondewo::nlu::GenerateResponsesRequest& request, ::ondewo::nlu::GenerateResponsesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::GenerateResponsesRequest, ::ondewo::nlu::GenerateResponsesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GenerateResponses_, context, request, response);
}

void AiServices::Stub::async::GenerateResponses(::grpc::ClientContext* context, const ::ondewo::nlu::GenerateResponsesRequest* request, ::ondewo::nlu::GenerateResponsesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::GenerateResponsesRequest, ::ondewo::nlu::GenerateResponsesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GenerateResponses_, context, request, response, std::move(f));
}

void AiServices::Stub::async::GenerateResponses(::grpc::ClientContext* context, const ::ondewo::nlu::GenerateResponsesRequest* request, ::ondewo::nlu::GenerateResponsesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GenerateResponses_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::GenerateResponsesResponse>* AiServices::Stub::PrepareAsyncGenerateResponsesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GenerateResponsesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::GenerateResponsesResponse, ::ondewo::nlu::GenerateResponsesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GenerateResponses_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::GenerateResponsesResponse>* AiServices::Stub::AsyncGenerateResponsesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GenerateResponsesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGenerateResponsesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AiServices::Stub::GetAlternativeSentences(::grpc::ClientContext* context, const ::ondewo::nlu::GetAlternativeSentencesRequest& request, ::ondewo::nlu::GetAlternativeSentencesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::GetAlternativeSentencesRequest, ::ondewo::nlu::GetAlternativeSentencesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAlternativeSentences_, context, request, response);
}

void AiServices::Stub::async::GetAlternativeSentences(::grpc::ClientContext* context, const ::ondewo::nlu::GetAlternativeSentencesRequest* request, ::ondewo::nlu::GetAlternativeSentencesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::GetAlternativeSentencesRequest, ::ondewo::nlu::GetAlternativeSentencesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAlternativeSentences_, context, request, response, std::move(f));
}

void AiServices::Stub::async::GetAlternativeSentences(::grpc::ClientContext* context, const ::ondewo::nlu::GetAlternativeSentencesRequest* request, ::ondewo::nlu::GetAlternativeSentencesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAlternativeSentences_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::GetAlternativeSentencesResponse>* AiServices::Stub::PrepareAsyncGetAlternativeSentencesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetAlternativeSentencesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::GetAlternativeSentencesResponse, ::ondewo::nlu::GetAlternativeSentencesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAlternativeSentences_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::GetAlternativeSentencesResponse>* AiServices::Stub::AsyncGetAlternativeSentencesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetAlternativeSentencesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAlternativeSentencesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AiServices::Stub::GetAlternativeTrainingPhrases(::grpc::ClientContext* context, const ::ondewo::nlu::GetAlternativeTrainingPhrasesRequest& request, ::ondewo::nlu::GetAlternativeTrainingPhrasesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::GetAlternativeTrainingPhrasesRequest, ::ondewo::nlu::GetAlternativeTrainingPhrasesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAlternativeTrainingPhrases_, context, request, response);
}

void AiServices::Stub::async::GetAlternativeTrainingPhrases(::grpc::ClientContext* context, const ::ondewo::nlu::GetAlternativeTrainingPhrasesRequest* request, ::ondewo::nlu::GetAlternativeTrainingPhrasesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::GetAlternativeTrainingPhrasesRequest, ::ondewo::nlu::GetAlternativeTrainingPhrasesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAlternativeTrainingPhrases_, context, request, response, std::move(f));
}

void AiServices::Stub::async::GetAlternativeTrainingPhrases(::grpc::ClientContext* context, const ::ondewo::nlu::GetAlternativeTrainingPhrasesRequest* request, ::ondewo::nlu::GetAlternativeTrainingPhrasesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAlternativeTrainingPhrases_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::GetAlternativeTrainingPhrasesResponse>* AiServices::Stub::PrepareAsyncGetAlternativeTrainingPhrasesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetAlternativeTrainingPhrasesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::GetAlternativeTrainingPhrasesResponse, ::ondewo::nlu::GetAlternativeTrainingPhrasesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAlternativeTrainingPhrases_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::GetAlternativeTrainingPhrasesResponse>* AiServices::Stub::AsyncGetAlternativeTrainingPhrasesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetAlternativeTrainingPhrasesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAlternativeTrainingPhrasesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AiServices::Stub::GetSynonyms(::grpc::ClientContext* context, const ::ondewo::nlu::GetSynonymsRequest& request, ::ondewo::nlu::GetSynonymsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::GetSynonymsRequest, ::ondewo::nlu::GetSynonymsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSynonyms_, context, request, response);
}

void AiServices::Stub::async::GetSynonyms(::grpc::ClientContext* context, const ::ondewo::nlu::GetSynonymsRequest* request, ::ondewo::nlu::GetSynonymsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::GetSynonymsRequest, ::ondewo::nlu::GetSynonymsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSynonyms_, context, request, response, std::move(f));
}

void AiServices::Stub::async::GetSynonyms(::grpc::ClientContext* context, const ::ondewo::nlu::GetSynonymsRequest* request, ::ondewo::nlu::GetSynonymsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSynonyms_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::GetSynonymsResponse>* AiServices::Stub::PrepareAsyncGetSynonymsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetSynonymsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::GetSynonymsResponse, ::ondewo::nlu::GetSynonymsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSynonyms_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::GetSynonymsResponse>* AiServices::Stub::AsyncGetSynonymsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetSynonymsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSynonymsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AiServices::Stub::ClassifyIntents(::grpc::ClientContext* context, const ::ondewo::nlu::ClassifyIntentsRequest& request, ::ondewo::nlu::ClassifyIntentsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::ClassifyIntentsRequest, ::ondewo::nlu::ClassifyIntentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ClassifyIntents_, context, request, response);
}

void AiServices::Stub::async::ClassifyIntents(::grpc::ClientContext* context, const ::ondewo::nlu::ClassifyIntentsRequest* request, ::ondewo::nlu::ClassifyIntentsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::ClassifyIntentsRequest, ::ondewo::nlu::ClassifyIntentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClassifyIntents_, context, request, response, std::move(f));
}

void AiServices::Stub::async::ClassifyIntents(::grpc::ClientContext* context, const ::ondewo::nlu::ClassifyIntentsRequest* request, ::ondewo::nlu::ClassifyIntentsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ClassifyIntents_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ClassifyIntentsResponse>* AiServices::Stub::PrepareAsyncClassifyIntentsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ClassifyIntentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::ClassifyIntentsResponse, ::ondewo::nlu::ClassifyIntentsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ClassifyIntents_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ClassifyIntentsResponse>* AiServices::Stub::AsyncClassifyIntentsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ClassifyIntentsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClassifyIntentsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AiServices::Stub::ExtractEntitiesFuzzy(::grpc::ClientContext* context, const ::ondewo::nlu::ExtractEntitiesFuzzyRequest& request, ::ondewo::nlu::ExtractEntitiesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::ExtractEntitiesFuzzyRequest, ::ondewo::nlu::ExtractEntitiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExtractEntitiesFuzzy_, context, request, response);
}

void AiServices::Stub::async::ExtractEntitiesFuzzy(::grpc::ClientContext* context, const ::ondewo::nlu::ExtractEntitiesFuzzyRequest* request, ::ondewo::nlu::ExtractEntitiesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::ExtractEntitiesFuzzyRequest, ::ondewo::nlu::ExtractEntitiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExtractEntitiesFuzzy_, context, request, response, std::move(f));
}

void AiServices::Stub::async::ExtractEntitiesFuzzy(::grpc::ClientContext* context, const ::ondewo::nlu::ExtractEntitiesFuzzyRequest* request, ::ondewo::nlu::ExtractEntitiesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExtractEntitiesFuzzy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ExtractEntitiesResponse>* AiServices::Stub::PrepareAsyncExtractEntitiesFuzzyRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ExtractEntitiesFuzzyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::ExtractEntitiesResponse, ::ondewo::nlu::ExtractEntitiesFuzzyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExtractEntitiesFuzzy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ExtractEntitiesResponse>* AiServices::Stub::AsyncExtractEntitiesFuzzyRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ExtractEntitiesFuzzyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExtractEntitiesFuzzyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AiServices::Stub::LlmGenerate(::grpc::ClientContext* context, const ::ondewo::nlu::LlmGenerateRequest& request, ::ondewo::nlu::LlmGenerateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::LlmGenerateRequest, ::ondewo::nlu::LlmGenerateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LlmGenerate_, context, request, response);
}

void AiServices::Stub::async::LlmGenerate(::grpc::ClientContext* context, const ::ondewo::nlu::LlmGenerateRequest* request, ::ondewo::nlu::LlmGenerateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::LlmGenerateRequest, ::ondewo::nlu::LlmGenerateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LlmGenerate_, context, request, response, std::move(f));
}

void AiServices::Stub::async::LlmGenerate(::grpc::ClientContext* context, const ::ondewo::nlu::LlmGenerateRequest* request, ::ondewo::nlu::LlmGenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LlmGenerate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::LlmGenerateResponse>* AiServices::Stub::PrepareAsyncLlmGenerateRaw(::grpc::ClientContext* context, const ::ondewo::nlu::LlmGenerateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::LlmGenerateResponse, ::ondewo::nlu::LlmGenerateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LlmGenerate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::LlmGenerateResponse>* AiServices::Stub::AsyncLlmGenerateRaw(::grpc::ClientContext* context, const ::ondewo::nlu::LlmGenerateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLlmGenerateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::ondewo::nlu::StreamingLlmGenerateResponse>* AiServices::Stub::StreamingLlmGenerateRaw(::grpc::ClientContext* context, const ::ondewo::nlu::LlmGenerateRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::ondewo::nlu::StreamingLlmGenerateResponse>::Create(channel_.get(), rpcmethod_StreamingLlmGenerate_, context, request);
}

void AiServices::Stub::async::StreamingLlmGenerate(::grpc::ClientContext* context, const ::ondewo::nlu::LlmGenerateRequest* request, ::grpc::ClientReadReactor< ::ondewo::nlu::StreamingLlmGenerateResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::ondewo::nlu::StreamingLlmGenerateResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamingLlmGenerate_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::ondewo::nlu::StreamingLlmGenerateResponse>* AiServices::Stub::AsyncStreamingLlmGenerateRaw(::grpc::ClientContext* context, const ::ondewo::nlu::LlmGenerateRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::ondewo::nlu::StreamingLlmGenerateResponse>::Create(channel_.get(), cq, rpcmethod_StreamingLlmGenerate_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::ondewo::nlu::StreamingLlmGenerateResponse>* AiServices::Stub::PrepareAsyncStreamingLlmGenerateRaw(::grpc::ClientContext* context, const ::ondewo::nlu::LlmGenerateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::ondewo::nlu::StreamingLlmGenerateResponse>::Create(channel_.get(), cq, rpcmethod_StreamingLlmGenerate_, context, request, false, nullptr);
}

::grpc::Status AiServices::Stub::ListLlmModels(::grpc::ClientContext* context, const ::ondewo::nlu::ListLlmModelsRequest& request, ::ondewo::nlu::ListLlmModelsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::ListLlmModelsRequest, ::ondewo::nlu::ListLlmModelsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListLlmModels_, context, request, response);
}

void AiServices::Stub::async::ListLlmModels(::grpc::ClientContext* context, const ::ondewo::nlu::ListLlmModelsRequest* request, ::ondewo::nlu::ListLlmModelsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::ListLlmModelsRequest, ::ondewo::nlu::ListLlmModelsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListLlmModels_, context, request, response, std::move(f));
}

void AiServices::Stub::async::ListLlmModels(::grpc::ClientContext* context, const ::ondewo::nlu::ListLlmModelsRequest* request, ::ondewo::nlu::ListLlmModelsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListLlmModels_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ListLlmModelsResponse>* AiServices::Stub::PrepareAsyncListLlmModelsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ListLlmModelsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::ListLlmModelsResponse, ::ondewo::nlu::ListLlmModelsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListLlmModels_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ListLlmModelsResponse>* AiServices::Stub::AsyncListLlmModelsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ListLlmModelsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListLlmModelsRaw(context, request, cq);
  result->StartCall();
  return result;
}

AiServices::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AiServices_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AiServices::Service, ::ondewo::nlu::ExtractEntitiesRequest, ::ondewo::nlu::ExtractEntitiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AiServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::ExtractEntitiesRequest* req,
             ::ondewo::nlu::ExtractEntitiesResponse* resp) {
               return service->ExtractEntities(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AiServices_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AiServices::Service, ::ondewo::nlu::GenerateUserSaysRequest, ::ondewo::nlu::GenerateUserSaysResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AiServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::GenerateUserSaysRequest* req,
             ::ondewo::nlu::GenerateUserSaysResponse* resp) {
               return service->GenerateUserSays(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AiServices_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AiServices::Service, ::ondewo::nlu::GenerateResponsesRequest, ::ondewo::nlu::GenerateResponsesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AiServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::GenerateResponsesRequest* req,
             ::ondewo::nlu::GenerateResponsesResponse* resp) {
               return service->GenerateResponses(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AiServices_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AiServices::Service, ::ondewo::nlu::GetAlternativeSentencesRequest, ::ondewo::nlu::GetAlternativeSentencesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AiServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::GetAlternativeSentencesRequest* req,
             ::ondewo::nlu::GetAlternativeSentencesResponse* resp) {
               return service->GetAlternativeSentences(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AiServices_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AiServices::Service, ::ondewo::nlu::GetAlternativeTrainingPhrasesRequest, ::ondewo::nlu::GetAlternativeTrainingPhrasesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AiServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::GetAlternativeTrainingPhrasesRequest* req,
             ::ondewo::nlu::GetAlternativeTrainingPhrasesResponse* resp) {
               return service->GetAlternativeTrainingPhrases(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AiServices_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AiServices::Service, ::ondewo::nlu::GetSynonymsRequest, ::ondewo::nlu::GetSynonymsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AiServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::GetSynonymsRequest* req,
             ::ondewo::nlu::GetSynonymsResponse* resp) {
               return service->GetSynonyms(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AiServices_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AiServices::Service, ::ondewo::nlu::ClassifyIntentsRequest, ::ondewo::nlu::ClassifyIntentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AiServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::ClassifyIntentsRequest* req,
             ::ondewo::nlu::ClassifyIntentsResponse* resp) {
               return service->ClassifyIntents(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AiServices_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AiServices::Service, ::ondewo::nlu::ExtractEntitiesFuzzyRequest, ::ondewo::nlu::ExtractEntitiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AiServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::ExtractEntitiesFuzzyRequest* req,
             ::ondewo::nlu::ExtractEntitiesResponse* resp) {
               return service->ExtractEntitiesFuzzy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AiServices_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AiServices::Service, ::ondewo::nlu::LlmGenerateRequest, ::ondewo::nlu::LlmGenerateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AiServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::LlmGenerateRequest* req,
             ::ondewo::nlu::LlmGenerateResponse* resp) {
               return service->LlmGenerate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AiServices_method_names[9],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< AiServices::Service, ::ondewo::nlu::LlmGenerateRequest, ::ondewo::nlu::StreamingLlmGenerateResponse>(
          [](AiServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::LlmGenerateRequest* req,
             ::grpc::ServerWriter<::ondewo::nlu::StreamingLlmGenerateResponse>* writer) {
               return service->StreamingLlmGenerate(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AiServices_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AiServices::Service, ::ondewo::nlu::ListLlmModelsRequest, ::ondewo::nlu::ListLlmModelsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AiServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::ListLlmModelsRequest* req,
             ::ondewo::nlu::ListLlmModelsResponse* resp) {
               return service->ListLlmModels(ctx, req, resp);
             }, this)));
}

AiServices::Service::~Service() {
}

::grpc::Status AiServices::Service::ExtractEntities(::grpc::ServerContext* context, const ::ondewo::nlu::ExtractEntitiesRequest* request, ::ondewo::nlu::ExtractEntitiesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AiServices::Service::GenerateUserSays(::grpc::ServerContext* context, const ::ondewo::nlu::GenerateUserSaysRequest* request, ::ondewo::nlu::GenerateUserSaysResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AiServices::Service::GenerateResponses(::grpc::ServerContext* context, const ::ondewo::nlu::GenerateResponsesRequest* request, ::ondewo::nlu::GenerateResponsesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AiServices::Service::GetAlternativeSentences(::grpc::ServerContext* context, const ::ondewo::nlu::GetAlternativeSentencesRequest* request, ::ondewo::nlu::GetAlternativeSentencesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AiServices::Service::GetAlternativeTrainingPhrases(::grpc::ServerContext* context, const ::ondewo::nlu::GetAlternativeTrainingPhrasesRequest* request, ::ondewo::nlu::GetAlternativeTrainingPhrasesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AiServices::Service::GetSynonyms(::grpc::ServerContext* context, const ::ondewo::nlu::GetSynonymsRequest* request, ::ondewo::nlu::GetSynonymsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AiServices::Service::ClassifyIntents(::grpc::ServerContext* context, const ::ondewo::nlu::ClassifyIntentsRequest* request, ::ondewo::nlu::ClassifyIntentsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AiServices::Service::ExtractEntitiesFuzzy(::grpc::ServerContext* context, const ::ondewo::nlu::ExtractEntitiesFuzzyRequest* request, ::ondewo::nlu::ExtractEntitiesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AiServices::Service::LlmGenerate(::grpc::ServerContext* context, const ::ondewo::nlu::LlmGenerateRequest* request, ::ondewo::nlu::LlmGenerateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AiServices::Service::StreamingLlmGenerate(::grpc::ServerContext* context, const ::ondewo::nlu::LlmGenerateRequest* request, ::grpc::ServerWriter< ::ondewo::nlu::StreamingLlmGenerateResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AiServices::Service::ListLlmModels(::grpc::ServerContext* context, const ::ondewo::nlu::ListLlmModelsRequest* request, ::ondewo::nlu::ListLlmModelsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ondewo
}  // namespace nlu

