// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ondewo/nlu/context.proto

#include "ondewo/nlu/context.pb.h"
#include "ondewo/nlu/context.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ondewo {
namespace nlu {

static const char* Contexts_method_names[] = {
  "/ondewo.nlu.Contexts/ListContexts",
  "/ondewo.nlu.Contexts/GetContext",
  "/ondewo.nlu.Contexts/CreateContext",
  "/ondewo.nlu.Contexts/UpdateContext",
  "/ondewo.nlu.Contexts/DeleteContext",
  "/ondewo.nlu.Contexts/DeleteAllContexts",
};

std::unique_ptr< Contexts::Stub> Contexts::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Contexts::Stub> stub(new Contexts::Stub(channel, options));
  return stub;
}

Contexts::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ListContexts_(Contexts_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetContext_(Contexts_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateContext_(Contexts_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateContext_(Contexts_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteContext_(Contexts_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteAllContexts_(Contexts_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Contexts::Stub::ListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::ondewo::nlu::ListContextsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::ListContextsRequest, ::ondewo::nlu::ListContextsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListContexts_, context, request, response);
}

void Contexts::Stub::async::ListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest* request, ::ondewo::nlu::ListContextsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::ListContextsRequest, ::ondewo::nlu::ListContextsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListContexts_, context, request, response, std::move(f));
}

void Contexts::Stub::async::ListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest* request, ::ondewo::nlu::ListContextsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListContexts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ListContextsResponse>* Contexts::Stub::PrepareAsyncListContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::ListContextsResponse, ::ondewo::nlu::ListContextsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListContexts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ListContextsResponse>* Contexts::Stub::AsyncListContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListContextsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Contexts::Stub::GetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::ondewo::nlu::Context* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::GetContextRequest, ::ondewo::nlu::Context, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetContext_, context, request, response);
}

void Contexts::Stub::async::GetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest* request, ::ondewo::nlu::Context* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::GetContextRequest, ::ondewo::nlu::Context, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContext_, context, request, response, std::move(f));
}

void Contexts::Stub::async::GetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest* request, ::ondewo::nlu::Context* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContext_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* Contexts::Stub::PrepareAsyncGetContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::Context, ::ondewo::nlu::GetContextRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetContext_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* Contexts::Stub::AsyncGetContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetContextRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Contexts::Stub::CreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::ondewo::nlu::Context* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::CreateContextRequest, ::ondewo::nlu::Context, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateContext_, context, request, response);
}

void Contexts::Stub::async::CreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest* request, ::ondewo::nlu::Context* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::CreateContextRequest, ::ondewo::nlu::Context, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateContext_, context, request, response, std::move(f));
}

void Contexts::Stub::async::CreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest* request, ::ondewo::nlu::Context* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateContext_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* Contexts::Stub::PrepareAsyncCreateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::Context, ::ondewo::nlu::CreateContextRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateContext_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* Contexts::Stub::AsyncCreateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateContextRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Contexts::Stub::UpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::ondewo::nlu::Context* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::UpdateContextRequest, ::ondewo::nlu::Context, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateContext_, context, request, response);
}

void Contexts::Stub::async::UpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest* request, ::ondewo::nlu::Context* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::UpdateContextRequest, ::ondewo::nlu::Context, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateContext_, context, request, response, std::move(f));
}

void Contexts::Stub::async::UpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest* request, ::ondewo::nlu::Context* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateContext_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* Contexts::Stub::PrepareAsyncUpdateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::Context, ::ondewo::nlu::UpdateContextRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateContext_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* Contexts::Stub::AsyncUpdateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateContextRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Contexts::Stub::DeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::DeleteContextRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteContext_, context, request, response);
}

void Contexts::Stub::async::DeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::DeleteContextRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteContext_, context, request, response, std::move(f));
}

void Contexts::Stub::async::DeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteContext_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Contexts::Stub::PrepareAsyncDeleteContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::ondewo::nlu::DeleteContextRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteContext_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Contexts::Stub::AsyncDeleteContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteContextRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Contexts::Stub::DeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::DeleteAllContextsRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteAllContexts_, context, request, response);
}

void Contexts::Stub::async::DeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::DeleteAllContextsRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAllContexts_, context, request, response, std::move(f));
}

void Contexts::Stub::async::DeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAllContexts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Contexts::Stub::PrepareAsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::ondewo::nlu::DeleteAllContextsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteAllContexts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* Contexts::Stub::AsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteAllContextsRaw(context, request, cq);
  result->StartCall();
  return result;
}

Contexts::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Contexts_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Contexts::Service, ::ondewo::nlu::ListContextsRequest, ::ondewo::nlu::ListContextsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Contexts::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::ListContextsRequest* req,
             ::ondewo::nlu::ListContextsResponse* resp) {
               return service->ListContexts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Contexts_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Contexts::Service, ::ondewo::nlu::GetContextRequest, ::ondewo::nlu::Context, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Contexts::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::GetContextRequest* req,
             ::ondewo::nlu::Context* resp) {
               return service->GetContext(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Contexts_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Contexts::Service, ::ondewo::nlu::CreateContextRequest, ::ondewo::nlu::Context, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Contexts::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::CreateContextRequest* req,
             ::ondewo::nlu::Context* resp) {
               return service->CreateContext(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Contexts_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Contexts::Service, ::ondewo::nlu::UpdateContextRequest, ::ondewo::nlu::Context, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Contexts::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::UpdateContextRequest* req,
             ::ondewo::nlu::Context* resp) {
               return service->UpdateContext(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Contexts_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Contexts::Service, ::ondewo::nlu::DeleteContextRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Contexts::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::DeleteContextRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->DeleteContext(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Contexts_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Contexts::Service, ::ondewo::nlu::DeleteAllContextsRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Contexts::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::DeleteAllContextsRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->DeleteAllContexts(ctx, req, resp);
             }, this)));
}

Contexts::Service::~Service() {
}

::grpc::Status Contexts::Service::ListContexts(::grpc::ServerContext* context, const ::ondewo::nlu::ListContextsRequest* request, ::ondewo::nlu::ListContextsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Contexts::Service::GetContext(::grpc::ServerContext* context, const ::ondewo::nlu::GetContextRequest* request, ::ondewo::nlu::Context* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Contexts::Service::CreateContext(::grpc::ServerContext* context, const ::ondewo::nlu::CreateContextRequest* request, ::ondewo::nlu::Context* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Contexts::Service::UpdateContext(::grpc::ServerContext* context, const ::ondewo::nlu::UpdateContextRequest* request, ::ondewo::nlu::Context* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Contexts::Service::DeleteContext(::grpc::ServerContext* context, const ::ondewo::nlu::DeleteContextRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Contexts::Service::DeleteAllContexts(::grpc::ServerContext* context, const ::ondewo::nlu::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ondewo
}  // namespace nlu

