// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ondewo/nlu/context.proto
// Original file comments:
// Copyright 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Modifications Copyright 2020-2026 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_ondewo_2fnlu_2fcontext_2eproto__INCLUDED
#define GRPC_ondewo_2fnlu_2fcontext_2eproto__INCLUDED

#include "ondewo/nlu/context.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ondewo {
namespace nlu {

// A context represents additional information included with user input or with an intent returned by the Dialogflow API. Contexts are helpful for differentiating user input which may be vague or have a different meaning depending on additional details from your application such as user setting and preferences, previous user input, where the user is in your application, geographic location, and so on.
//
// You can include contexts as input parameters of a <a href="index.html#ondewo.nlu.Sessions.DetectIntent">DetectIntent</a> (or <a href="index.html#ondewo.nlu.Sessions.StreamingDetectIntent">StreamingDetectIntent</a>) request, or as output contexts included in the returned intent.
// Contexts expire when an intent is matched, after the number of <code>DetectIntent</code> requests specified by the <code>lifespan_count</code> parameter, or after 10 minutes if no intents are matched for a <code>DetectIntent</code> request.
// For more information about contexts, see the <a href="https://dialogflow.com/docs/contexts">Dialogflow documentation</a>.
class Contexts final {
 public:
  static constexpr char const* service_full_name() {
    return "ondewo.nlu.Contexts";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Returns the list of all contexts in the specified session.
    virtual ::grpc::Status ListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::ondewo::nlu::ListContextsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::ListContextsResponse>> AsyncListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::ListContextsResponse>>(AsyncListContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::ListContextsResponse>> PrepareAsyncListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::ListContextsResponse>>(PrepareAsyncListContextsRaw(context, request, cq));
    }
    // Retrieves the specified context.
    virtual ::grpc::Status GetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::ondewo::nlu::Context* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>> AsyncGetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>>(AsyncGetContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>> PrepareAsyncGetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>>(PrepareAsyncGetContextRaw(context, request, cq));
    }
    // Creates a context.
    virtual ::grpc::Status CreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::ondewo::nlu::Context* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>> AsyncCreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>>(AsyncCreateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>> PrepareAsyncCreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>>(PrepareAsyncCreateContextRaw(context, request, cq));
    }
    // Updates the specified context.
    virtual ::grpc::Status UpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::ondewo::nlu::Context* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>> AsyncUpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>>(AsyncUpdateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>> PrepareAsyncUpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>>(PrepareAsyncUpdateContextRaw(context, request, cq));
    }
    // Deletes the specified context.
    virtual ::grpc::Status DeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncDeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncDeleteContextRaw(context, request, cq));
    }
    // Deletes all active contexts in the specified session.
    virtual ::grpc::Status DeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncDeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncDeleteAllContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncDeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncDeleteAllContextsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Returns the list of all contexts in the specified session.
      virtual void ListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest* request, ::ondewo::nlu::ListContextsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest* request, ::ondewo::nlu::ListContextsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Retrieves the specified context.
      virtual void GetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest* request, ::ondewo::nlu::Context* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest* request, ::ondewo::nlu::Context* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Creates a context.
      virtual void CreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest* request, ::ondewo::nlu::Context* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest* request, ::ondewo::nlu::Context* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Updates the specified context.
      virtual void UpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest* request, ::ondewo::nlu::Context* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest* request, ::ondewo::nlu::Context* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Deletes the specified context.
      virtual void DeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Deletes all active contexts in the specified session.
      virtual void DeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::ListContextsResponse>* AsyncListContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::ListContextsResponse>* PrepareAsyncListContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>* AsyncGetContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>* PrepareAsyncGetContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>* AsyncCreateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>* PrepareAsyncCreateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>* AsyncUpdateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::Context>* PrepareAsyncUpdateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncDeleteContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::ondewo::nlu::ListContextsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ListContextsResponse>> AsyncListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ListContextsResponse>>(AsyncListContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ListContextsResponse>> PrepareAsyncListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ListContextsResponse>>(PrepareAsyncListContextsRaw(context, request, cq));
    }
    ::grpc::Status GetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::ondewo::nlu::Context* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>> AsyncGetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>>(AsyncGetContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>> PrepareAsyncGetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>>(PrepareAsyncGetContextRaw(context, request, cq));
    }
    ::grpc::Status CreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::ondewo::nlu::Context* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>> AsyncCreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>>(AsyncCreateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>> PrepareAsyncCreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>>(PrepareAsyncCreateContextRaw(context, request, cq));
    }
    ::grpc::Status UpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::ondewo::nlu::Context* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>> AsyncUpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>>(AsyncUpdateContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>> PrepareAsyncUpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>>(PrepareAsyncUpdateContextRaw(context, request, cq));
    }
    ::grpc::Status DeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteContextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncDeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncDeleteContextRaw(context, request, cq));
    }
    ::grpc::Status DeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncDeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncDeleteAllContextsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncDeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncDeleteAllContextsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest* request, ::ondewo::nlu::ListContextsResponse* response, std::function<void(::grpc::Status)>) override;
      void ListContexts(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest* request, ::ondewo::nlu::ListContextsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest* request, ::ondewo::nlu::Context* response, std::function<void(::grpc::Status)>) override;
      void GetContext(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest* request, ::ondewo::nlu::Context* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest* request, ::ondewo::nlu::Context* response, std::function<void(::grpc::Status)>) override;
      void CreateContext(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest* request, ::ondewo::nlu::Context* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest* request, ::ondewo::nlu::Context* response, std::function<void(::grpc::Status)>) override;
      void UpdateContext(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest* request, ::ondewo::nlu::Context* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void DeleteContext(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void DeleteAllContexts(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ListContextsResponse>* AsyncListContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ListContextsResponse>* PrepareAsyncListContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ListContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* AsyncGetContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* PrepareAsyncGetContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* AsyncCreateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* PrepareAsyncCreateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CreateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* AsyncUpdateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::Context>* PrepareAsyncUpdateContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::UpdateContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncDeleteContextRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteContextRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncDeleteAllContextsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::DeleteAllContextsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListContexts_;
    const ::grpc::internal::RpcMethod rpcmethod_GetContext_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateContext_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateContext_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteContext_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteAllContexts_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Returns the list of all contexts in the specified session.
    virtual ::grpc::Status ListContexts(::grpc::ServerContext* context, const ::ondewo::nlu::ListContextsRequest* request, ::ondewo::nlu::ListContextsResponse* response);
    // Retrieves the specified context.
    virtual ::grpc::Status GetContext(::grpc::ServerContext* context, const ::ondewo::nlu::GetContextRequest* request, ::ondewo::nlu::Context* response);
    // Creates a context.
    virtual ::grpc::Status CreateContext(::grpc::ServerContext* context, const ::ondewo::nlu::CreateContextRequest* request, ::ondewo::nlu::Context* response);
    // Updates the specified context.
    virtual ::grpc::Status UpdateContext(::grpc::ServerContext* context, const ::ondewo::nlu::UpdateContextRequest* request, ::ondewo::nlu::Context* response);
    // Deletes the specified context.
    virtual ::grpc::Status DeleteContext(::grpc::ServerContext* context, const ::ondewo::nlu::DeleteContextRequest* request, ::google::protobuf::Empty* response);
    // Deletes all active contexts in the specified session.
    virtual ::grpc::Status DeleteAllContexts(::grpc::ServerContext* context, const ::ondewo::nlu::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListContexts() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::ListContextsRequest* /*request*/, ::ondewo::nlu::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListContexts(::grpc::ServerContext* context, ::ondewo::nlu::ListContextsRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::nlu::ListContextsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetContext() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetContext(::grpc::ServerContext* context, ::ondewo::nlu::GetContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::nlu::Context>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateContext() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::CreateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateContext(::grpc::ServerContext* context, ::ondewo::nlu::CreateContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::nlu::Context>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateContext() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::UpdateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateContext(::grpc::ServerContext* context, ::ondewo::nlu::UpdateContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::nlu::Context>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteContext() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteContext(::grpc::ServerContext* context, ::ondewo::nlu::DeleteContextRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteAllContexts(::grpc::ServerContext* context, ::ondewo::nlu::DeleteAllContextsRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListContexts<WithAsyncMethod_GetContext<WithAsyncMethod_CreateContext<WithAsyncMethod_UpdateContext<WithAsyncMethod_DeleteContext<WithAsyncMethod_DeleteAllContexts<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListContexts() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::ListContextsRequest, ::ondewo::nlu::ListContextsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::nlu::ListContextsRequest* request, ::ondewo::nlu::ListContextsResponse* response) { return this->ListContexts(context, request, response); }));}
    void SetMessageAllocatorFor_ListContexts(
        ::grpc::MessageAllocator< ::ondewo::nlu::ListContextsRequest, ::ondewo::nlu::ListContextsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::ListContextsRequest, ::ondewo::nlu::ListContextsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::ListContextsRequest* /*request*/, ::ondewo::nlu::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListContexts(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::nlu::ListContextsRequest* /*request*/, ::ondewo::nlu::ListContextsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetContext() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::GetContextRequest, ::ondewo::nlu::Context>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::nlu::GetContextRequest* request, ::ondewo::nlu::Context* response) { return this->GetContext(context, request, response); }));}
    void SetMessageAllocatorFor_GetContext(
        ::grpc::MessageAllocator< ::ondewo::nlu::GetContextRequest, ::ondewo::nlu::Context>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::GetContextRequest, ::ondewo::nlu::Context>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetContext(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::nlu::GetContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateContext() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::CreateContextRequest, ::ondewo::nlu::Context>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::nlu::CreateContextRequest* request, ::ondewo::nlu::Context* response) { return this->CreateContext(context, request, response); }));}
    void SetMessageAllocatorFor_CreateContext(
        ::grpc::MessageAllocator< ::ondewo::nlu::CreateContextRequest, ::ondewo::nlu::Context>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::CreateContextRequest, ::ondewo::nlu::Context>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::CreateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateContext(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::nlu::CreateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateContext() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::UpdateContextRequest, ::ondewo::nlu::Context>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::nlu::UpdateContextRequest* request, ::ondewo::nlu::Context* response) { return this->UpdateContext(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateContext(
        ::grpc::MessageAllocator< ::ondewo::nlu::UpdateContextRequest, ::ondewo::nlu::Context>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::UpdateContextRequest, ::ondewo::nlu::Context>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::UpdateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateContext(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::nlu::UpdateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteContext() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::DeleteContextRequest, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::nlu::DeleteContextRequest* request, ::google::protobuf::Empty* response) { return this->DeleteContext(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteContext(
        ::grpc::MessageAllocator< ::ondewo::nlu::DeleteContextRequest, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::DeleteContextRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteContext(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::nlu::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::DeleteAllContextsRequest, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::nlu::DeleteAllContextsRequest* request, ::google::protobuf::Empty* response) { return this->DeleteAllContexts(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteAllContexts(
        ::grpc::MessageAllocator< ::ondewo::nlu::DeleteAllContextsRequest, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::DeleteAllContextsRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteAllContexts(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::nlu::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ListContexts<WithCallbackMethod_GetContext<WithCallbackMethod_CreateContext<WithCallbackMethod_UpdateContext<WithCallbackMethod_DeleteContext<WithCallbackMethod_DeleteAllContexts<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListContexts() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::ListContextsRequest* /*request*/, ::ondewo::nlu::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetContext() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateContext() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::CreateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateContext() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::UpdateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteContext() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListContexts() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::ListContextsRequest* /*request*/, ::ondewo::nlu::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListContexts(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetContext() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetContext(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateContext() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::CreateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateContext(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateContext() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::UpdateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateContext(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteContext() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteContext(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteAllContexts(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListContexts() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListContexts(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::ListContextsRequest* /*request*/, ::ondewo::nlu::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListContexts(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetContext() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetContext(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetContext(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateContext() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateContext(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::CreateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateContext(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateContext() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateContext(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::UpdateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateContext(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteContext() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteContext(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteContext(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteAllContexts(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteAllContexts(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListContexts() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::nlu::ListContextsRequest, ::ondewo::nlu::ListContextsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::nlu::ListContextsRequest, ::ondewo::nlu::ListContextsResponse>* streamer) {
                       return this->StreamedListContexts(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::ListContextsRequest* /*request*/, ::ondewo::nlu::ListContextsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListContexts(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::nlu::ListContextsRequest,::ondewo::nlu::ListContextsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetContext() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::nlu::GetContextRequest, ::ondewo::nlu::Context>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::nlu::GetContextRequest, ::ondewo::nlu::Context>* streamer) {
                       return this->StreamedGetContext(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::nlu::GetContextRequest,::ondewo::nlu::Context>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateContext() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::nlu::CreateContextRequest, ::ondewo::nlu::Context>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::nlu::CreateContextRequest, ::ondewo::nlu::Context>* streamer) {
                       return this->StreamedCreateContext(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::CreateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::nlu::CreateContextRequest,::ondewo::nlu::Context>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateContext() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::nlu::UpdateContextRequest, ::ondewo::nlu::Context>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::nlu::UpdateContextRequest, ::ondewo::nlu::Context>* streamer) {
                       return this->StreamedUpdateContext(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::UpdateContextRequest* /*request*/, ::ondewo::nlu::Context* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::nlu::UpdateContextRequest,::ondewo::nlu::Context>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteContext : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteContext() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::nlu::DeleteContextRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::nlu::DeleteContextRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedDeleteContext(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteContext() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteContext(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteContextRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteContext(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::nlu::DeleteContextRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteAllContexts : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteAllContexts() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::nlu::DeleteAllContextsRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::nlu::DeleteAllContextsRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedDeleteAllContexts(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteAllContexts() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteAllContexts(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::DeleteAllContextsRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteAllContexts(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::nlu::DeleteAllContextsRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListContexts<WithStreamedUnaryMethod_GetContext<WithStreamedUnaryMethod_CreateContext<WithStreamedUnaryMethod_UpdateContext<WithStreamedUnaryMethod_DeleteContext<WithStreamedUnaryMethod_DeleteAllContexts<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ListContexts<WithStreamedUnaryMethod_GetContext<WithStreamedUnaryMethod_CreateContext<WithStreamedUnaryMethod_UpdateContext<WithStreamedUnaryMethod_DeleteContext<WithStreamedUnaryMethod_DeleteAllContexts<Service > > > > > > StreamedService;
};

}  // namespace nlu
}  // namespace ondewo


#endif  // GRPC_ondewo_2fnlu_2fcontext_2eproto__INCLUDED
