// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ondewo/nlu/operation_metadata.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ondewo_2fnlu_2foperation_5fmetadata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ondewo_2fnlu_2foperation_5fmetadata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ondewo_2fnlu_2foperation_5fmetadata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ondewo_2fnlu_2foperation_5fmetadata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ondewo_2fnlu_2foperation_5fmetadata_2eproto;
namespace ondewo {
namespace nlu {
class OperationMetadata;
struct OperationMetadataDefaultTypeInternal;
extern OperationMetadataDefaultTypeInternal _OperationMetadata_default_instance_;
}  // namespace nlu
}  // namespace ondewo
PROTOBUF_NAMESPACE_OPEN
template<> ::ondewo::nlu::OperationMetadata* Arena::CreateMaybeMessage<::ondewo::nlu::OperationMetadata>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ondewo {
namespace nlu {

enum OperationMetadata_Status : int {
  OperationMetadata_Status_STATUS_UNSPECIFIED = 0,
  OperationMetadata_Status_NOT_STARTED = 1,
  OperationMetadata_Status_IN_PROGRESS = 2,
  OperationMetadata_Status_DONE = 3,
  OperationMetadata_Status_CANCELLED = 4,
  OperationMetadata_Status_FAILED = 5,
  OperationMetadata_Status_OperationMetadata_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  OperationMetadata_Status_OperationMetadata_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool OperationMetadata_Status_IsValid(int value);
constexpr OperationMetadata_Status OperationMetadata_Status_Status_MIN = OperationMetadata_Status_STATUS_UNSPECIFIED;
constexpr OperationMetadata_Status OperationMetadata_Status_Status_MAX = OperationMetadata_Status_FAILED;
constexpr int OperationMetadata_Status_Status_ARRAYSIZE = OperationMetadata_Status_Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OperationMetadata_Status_descriptor();
template<typename T>
inline const std::string& OperationMetadata_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, OperationMetadata_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function OperationMetadata_Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    OperationMetadata_Status_descriptor(), enum_t_value);
}
inline bool OperationMetadata_Status_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, OperationMetadata_Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<OperationMetadata_Status>(
    OperationMetadata_Status_descriptor(), name, value);
}
enum OperationMetadata_OperationType : int {
  OperationMetadata_OperationType_OPERATION_TYPE_UNSPECIFIED = 0,
  OperationMetadata_OperationType_CREATE_AGENT = 1,
  OperationMetadata_OperationType_IMPORT_AGENT = 2,
  OperationMetadata_OperationType_EXPORT_AGENT = 3,
  OperationMetadata_OperationType_DELETE_AGENT = 4,
  OperationMetadata_OperationType_RESTORE_AGENT = 5,
  OperationMetadata_OperationType_BUILD_AGENT_CACHE = 6,
  OperationMetadata_OperationType_TRAIN_AGENT = 7,
  OperationMetadata_OperationType_EXPORT_BENCHMARK_AGENT = 8,
  OperationMetadata_OperationType_INDEX_AGENT = 9,
  OperationMetadata_OperationType_RUN_RAG_CRAWLER = 10,
  OperationMetadata_OperationType_ADD_RAG_CRAWLER_RESULT_TO_DATASET = 11,
  OperationMetadata_OperationType_REMOVE_RAG_CRAWLER_RESULT_FROM_DATASET = 12,
  OperationMetadata_OperationType_CHANGE_DATASET_EMBEDDING_MODEL = 13,
  OperationMetadata_OperationType_OperationMetadata_OperationType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  OperationMetadata_OperationType_OperationMetadata_OperationType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool OperationMetadata_OperationType_IsValid(int value);
constexpr OperationMetadata_OperationType OperationMetadata_OperationType_OperationType_MIN = OperationMetadata_OperationType_OPERATION_TYPE_UNSPECIFIED;
constexpr OperationMetadata_OperationType OperationMetadata_OperationType_OperationType_MAX = OperationMetadata_OperationType_CHANGE_DATASET_EMBEDDING_MODEL;
constexpr int OperationMetadata_OperationType_OperationType_ARRAYSIZE = OperationMetadata_OperationType_OperationType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* OperationMetadata_OperationType_descriptor();
template<typename T>
inline const std::string& OperationMetadata_OperationType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, OperationMetadata_OperationType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function OperationMetadata_OperationType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    OperationMetadata_OperationType_descriptor(), enum_t_value);
}
inline bool OperationMetadata_OperationType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, OperationMetadata_OperationType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<OperationMetadata_OperationType>(
    OperationMetadata_OperationType_descriptor(), name, value);
}
// ===================================================================

class OperationMetadata final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ondewo.nlu.OperationMetadata) */ {
 public:
  inline OperationMetadata() : OperationMetadata(nullptr) {}
  ~OperationMetadata() override;
  explicit PROTOBUF_CONSTEXPR OperationMetadata(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OperationMetadata(const OperationMetadata& from);
  OperationMetadata(OperationMetadata&& from) noexcept
    : OperationMetadata() {
    *this = ::std::move(from);
  }

  inline OperationMetadata& operator=(const OperationMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline OperationMetadata& operator=(OperationMetadata&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OperationMetadata& default_instance() {
    return *internal_default_instance();
  }
  static inline const OperationMetadata* internal_default_instance() {
    return reinterpret_cast<const OperationMetadata*>(
               &_OperationMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(OperationMetadata& a, OperationMetadata& b) {
    a.Swap(&b);
  }
  inline void Swap(OperationMetadata* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OperationMetadata* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  OperationMetadata* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<OperationMetadata>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OperationMetadata& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const OperationMetadata& from) {
    OperationMetadata::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OperationMetadata* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ondewo.nlu.OperationMetadata";
  }
  protected:
  explicit OperationMetadata(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef OperationMetadata_Status Status;
  static constexpr Status STATUS_UNSPECIFIED =
    OperationMetadata_Status_STATUS_UNSPECIFIED;
  static constexpr Status NOT_STARTED =
    OperationMetadata_Status_NOT_STARTED;
  static constexpr Status IN_PROGRESS =
    OperationMetadata_Status_IN_PROGRESS;
  static constexpr Status DONE =
    OperationMetadata_Status_DONE;
  static constexpr Status CANCELLED =
    OperationMetadata_Status_CANCELLED;
  static constexpr Status FAILED =
    OperationMetadata_Status_FAILED;
  static inline bool Status_IsValid(int value) {
    return OperationMetadata_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    OperationMetadata_Status_Status_MIN;
  static constexpr Status Status_MAX =
    OperationMetadata_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    OperationMetadata_Status_Status_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Status_descriptor() {
    return OperationMetadata_Status_descriptor();
  }
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return OperationMetadata_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Status* value) {
    return OperationMetadata_Status_Parse(name, value);
  }

  typedef OperationMetadata_OperationType OperationType;
  static constexpr OperationType OPERATION_TYPE_UNSPECIFIED =
    OperationMetadata_OperationType_OPERATION_TYPE_UNSPECIFIED;
  static constexpr OperationType CREATE_AGENT =
    OperationMetadata_OperationType_CREATE_AGENT;
  static constexpr OperationType IMPORT_AGENT =
    OperationMetadata_OperationType_IMPORT_AGENT;
  static constexpr OperationType EXPORT_AGENT =
    OperationMetadata_OperationType_EXPORT_AGENT;
  static constexpr OperationType DELETE_AGENT =
    OperationMetadata_OperationType_DELETE_AGENT;
  static constexpr OperationType RESTORE_AGENT =
    OperationMetadata_OperationType_RESTORE_AGENT;
  static constexpr OperationType BUILD_AGENT_CACHE =
    OperationMetadata_OperationType_BUILD_AGENT_CACHE;
  static constexpr OperationType TRAIN_AGENT =
    OperationMetadata_OperationType_TRAIN_AGENT;
  static constexpr OperationType EXPORT_BENCHMARK_AGENT =
    OperationMetadata_OperationType_EXPORT_BENCHMARK_AGENT;
  static constexpr OperationType INDEX_AGENT =
    OperationMetadata_OperationType_INDEX_AGENT;
  static constexpr OperationType RUN_RAG_CRAWLER =
    OperationMetadata_OperationType_RUN_RAG_CRAWLER;
  static constexpr OperationType ADD_RAG_CRAWLER_RESULT_TO_DATASET =
    OperationMetadata_OperationType_ADD_RAG_CRAWLER_RESULT_TO_DATASET;
  static constexpr OperationType REMOVE_RAG_CRAWLER_RESULT_FROM_DATASET =
    OperationMetadata_OperationType_REMOVE_RAG_CRAWLER_RESULT_FROM_DATASET;
  static constexpr OperationType CHANGE_DATASET_EMBEDDING_MODEL =
    OperationMetadata_OperationType_CHANGE_DATASET_EMBEDDING_MODEL;
  static inline bool OperationType_IsValid(int value) {
    return OperationMetadata_OperationType_IsValid(value);
  }
  static constexpr OperationType OperationType_MIN =
    OperationMetadata_OperationType_OperationType_MIN;
  static constexpr OperationType OperationType_MAX =
    OperationMetadata_OperationType_OperationType_MAX;
  static constexpr int OperationType_ARRAYSIZE =
    OperationMetadata_OperationType_OperationType_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  OperationType_descriptor() {
    return OperationMetadata_OperationType_descriptor();
  }
  template<typename T>
  static inline const std::string& OperationType_Name(T enum_t_value) {
    static_assert(::std::is_same<T, OperationType>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function OperationType_Name.");
    return OperationMetadata_OperationType_Name(enum_t_value);
  }
  static inline bool OperationType_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      OperationType* value) {
    return OperationMetadata_OperationType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSubOperationNamesFieldNumber = 3,
    kLogFieldNumber = 17,
    kParentOperationNameFieldNumber = 2,
    kCancelCommandFieldNumber = 8,
    kUserIdCreatedFieldNumber = 9,
    kUserIdCancelledFieldNumber = 10,
    kProjectParentFieldNumber = 11,
    kHostNameFieldNumber = 13,
    kDescriptionFieldNumber = 16,
    kCreatedByFieldNumber = 21,
    kModifiedByFieldNumber = 22,
    kCreateTimeFieldNumber = 4,
    kStartTimeFieldNumber = 5,
    kEndTimeFieldNumber = 6,
    kCreatedAtFieldNumber = 19,
    kModifiedAtFieldNumber = 20,
    kStatusFieldNumber = 1,
    kIsCancellationRequestedFieldNumber = 7,
    kOperationTypeFieldNumber = 12,
    kNumRerunsFieldNumber = 14,
    kMaxNumRerunsFieldNumber = 15,
    kLogLimitFieldNumber = 18,
  };
  // repeated string sub_operation_names = 3;
  int sub_operation_names_size() const;
  private:
  int _internal_sub_operation_names_size() const;
  public:
  void clear_sub_operation_names();
  const std::string& sub_operation_names(int index) const;
  std::string* mutable_sub_operation_names(int index);
  void set_sub_operation_names(int index, const std::string& value);
  void set_sub_operation_names(int index, std::string&& value);
  void set_sub_operation_names(int index, const char* value);
  void set_sub_operation_names(int index, const char* value, size_t size);
  std::string* add_sub_operation_names();
  void add_sub_operation_names(const std::string& value);
  void add_sub_operation_names(std::string&& value);
  void add_sub_operation_names(const char* value);
  void add_sub_operation_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& sub_operation_names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_sub_operation_names();
  private:
  const std::string& _internal_sub_operation_names(int index) const;
  std::string* _internal_add_sub_operation_names();
  public:

  // repeated string log = 17;
  int log_size() const;
  private:
  int _internal_log_size() const;
  public:
  void clear_log();
  const std::string& log(int index) const;
  std::string* mutable_log(int index);
  void set_log(int index, const std::string& value);
  void set_log(int index, std::string&& value);
  void set_log(int index, const char* value);
  void set_log(int index, const char* value, size_t size);
  std::string* add_log();
  void add_log(const std::string& value);
  void add_log(std::string&& value);
  void add_log(const char* value);
  void add_log(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& log() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_log();
  private:
  const std::string& _internal_log(int index) const;
  std::string* _internal_add_log();
  public:

  // string parent_operation_name = 2;
  void clear_parent_operation_name();
  const std::string& parent_operation_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_parent_operation_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_parent_operation_name();
  PROTOBUF_NODISCARD std::string* release_parent_operation_name();
  void set_allocated_parent_operation_name(std::string* parent_operation_name);
  private:
  const std::string& _internal_parent_operation_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_parent_operation_name(const std::string& value);
  std::string* _internal_mutable_parent_operation_name();
  public:

  // string cancel_command = 8;
  void clear_cancel_command();
  const std::string& cancel_command() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cancel_command(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cancel_command();
  PROTOBUF_NODISCARD std::string* release_cancel_command();
  void set_allocated_cancel_command(std::string* cancel_command);
  private:
  const std::string& _internal_cancel_command() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cancel_command(const std::string& value);
  std::string* _internal_mutable_cancel_command();
  public:

  // string user_id_created = 9;
  void clear_user_id_created();
  const std::string& user_id_created() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id_created(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id_created();
  PROTOBUF_NODISCARD std::string* release_user_id_created();
  void set_allocated_user_id_created(std::string* user_id_created);
  private:
  const std::string& _internal_user_id_created() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id_created(const std::string& value);
  std::string* _internal_mutable_user_id_created();
  public:

  // string user_id_cancelled = 10;
  void clear_user_id_cancelled();
  const std::string& user_id_cancelled() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_id_cancelled(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_id_cancelled();
  PROTOBUF_NODISCARD std::string* release_user_id_cancelled();
  void set_allocated_user_id_cancelled(std::string* user_id_cancelled);
  private:
  const std::string& _internal_user_id_cancelled() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_id_cancelled(const std::string& value);
  std::string* _internal_mutable_user_id_cancelled();
  public:

  // string project_parent = 11;
  void clear_project_parent();
  const std::string& project_parent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_project_parent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_project_parent();
  PROTOBUF_NODISCARD std::string* release_project_parent();
  void set_allocated_project_parent(std::string* project_parent);
  private:
  const std::string& _internal_project_parent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_project_parent(const std::string& value);
  std::string* _internal_mutable_project_parent();
  public:

  // string host_name = 13;
  void clear_host_name();
  const std::string& host_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_host_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_host_name();
  PROTOBUF_NODISCARD std::string* release_host_name();
  void set_allocated_host_name(std::string* host_name);
  private:
  const std::string& _internal_host_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_host_name(const std::string& value);
  std::string* _internal_mutable_host_name();
  public:

  // string description = 16;
  void clear_description();
  const std::string& description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_description();
  PROTOBUF_NODISCARD std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // string created_by = 21;
  void clear_created_by();
  const std::string& created_by() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_created_by(ArgT0&& arg0, ArgT... args);
  std::string* mutable_created_by();
  PROTOBUF_NODISCARD std::string* release_created_by();
  void set_allocated_created_by(std::string* created_by);
  private:
  const std::string& _internal_created_by() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_created_by(const std::string& value);
  std::string* _internal_mutable_created_by();
  public:

  // string modified_by = 22;
  void clear_modified_by();
  const std::string& modified_by() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_modified_by(ArgT0&& arg0, ArgT... args);
  std::string* mutable_modified_by();
  PROTOBUF_NODISCARD std::string* release_modified_by();
  void set_allocated_modified_by(std::string* modified_by);
  private:
  const std::string& _internal_modified_by() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_modified_by(const std::string& value);
  std::string* _internal_mutable_modified_by();
  public:

  // .google.protobuf.Timestamp create_time = 4;
  bool has_create_time() const;
  private:
  bool _internal_has_create_time() const;
  public:
  void clear_create_time();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& create_time() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_create_time();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_create_time();
  void set_allocated_create_time(::PROTOBUF_NAMESPACE_ID::Timestamp* create_time);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_create_time() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_create_time();
  public:
  void unsafe_arena_set_allocated_create_time(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* create_time);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_create_time();

  // .google.protobuf.Timestamp start_time = 5;
  bool has_start_time() const;
  private:
  bool _internal_has_start_time() const;
  public:
  void clear_start_time();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& start_time() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_start_time();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_start_time();
  void set_allocated_start_time(::PROTOBUF_NAMESPACE_ID::Timestamp* start_time);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_start_time() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_start_time();
  public:
  void unsafe_arena_set_allocated_start_time(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* start_time);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_start_time();

  // .google.protobuf.Timestamp end_time = 6;
  bool has_end_time() const;
  private:
  bool _internal_has_end_time() const;
  public:
  void clear_end_time();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& end_time() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_end_time();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_end_time();
  void set_allocated_end_time(::PROTOBUF_NAMESPACE_ID::Timestamp* end_time);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_end_time() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_end_time();
  public:
  void unsafe_arena_set_allocated_end_time(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* end_time);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_end_time();

  // .google.protobuf.Timestamp created_at = 19;
  bool has_created_at() const;
  private:
  bool _internal_has_created_at() const;
  public:
  void clear_created_at();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& created_at() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_created_at();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_created_at();
  void set_allocated_created_at(::PROTOBUF_NAMESPACE_ID::Timestamp* created_at);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_created_at() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_created_at();
  public:
  void unsafe_arena_set_allocated_created_at(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* created_at);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_created_at();

  // .google.protobuf.Timestamp modified_at = 20;
  bool has_modified_at() const;
  private:
  bool _internal_has_modified_at() const;
  public:
  void clear_modified_at();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& modified_at() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_modified_at();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_modified_at();
  void set_allocated_modified_at(::PROTOBUF_NAMESPACE_ID::Timestamp* modified_at);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_modified_at() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_modified_at();
  public:
  void unsafe_arena_set_allocated_modified_at(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* modified_at);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_modified_at();

  // .ondewo.nlu.OperationMetadata.Status status = 1;
  void clear_status();
  ::ondewo::nlu::OperationMetadata_Status status() const;
  void set_status(::ondewo::nlu::OperationMetadata_Status value);
  private:
  ::ondewo::nlu::OperationMetadata_Status _internal_status() const;
  void _internal_set_status(::ondewo::nlu::OperationMetadata_Status value);
  public:

  // bool is_cancellation_requested = 7;
  void clear_is_cancellation_requested();
  bool is_cancellation_requested() const;
  void set_is_cancellation_requested(bool value);
  private:
  bool _internal_is_cancellation_requested() const;
  void _internal_set_is_cancellation_requested(bool value);
  public:

  // .ondewo.nlu.OperationMetadata.OperationType operation_type = 12;
  void clear_operation_type();
  ::ondewo::nlu::OperationMetadata_OperationType operation_type() const;
  void set_operation_type(::ondewo::nlu::OperationMetadata_OperationType value);
  private:
  ::ondewo::nlu::OperationMetadata_OperationType _internal_operation_type() const;
  void _internal_set_operation_type(::ondewo::nlu::OperationMetadata_OperationType value);
  public:

  // int32 num_reruns = 14;
  void clear_num_reruns();
  int32_t num_reruns() const;
  void set_num_reruns(int32_t value);
  private:
  int32_t _internal_num_reruns() const;
  void _internal_set_num_reruns(int32_t value);
  public:

  // int32 max_num_reruns = 15;
  void clear_max_num_reruns();
  int32_t max_num_reruns() const;
  void set_max_num_reruns(int32_t value);
  private:
  int32_t _internal_max_num_reruns() const;
  void _internal_set_max_num_reruns(int32_t value);
  public:

  // int32 log_limit = 18;
  void clear_log_limit();
  int32_t log_limit() const;
  void set_log_limit(int32_t value);
  private:
  int32_t _internal_log_limit() const;
  void _internal_set_log_limit(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ondewo.nlu.OperationMetadata)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> sub_operation_names_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> log_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr parent_operation_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cancel_command_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_created_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_cancelled_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr project_parent_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr host_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr created_by_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr modified_by_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* create_time_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* start_time_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* end_time_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* created_at_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* modified_at_;
    int status_;
    bool is_cancellation_requested_;
    int operation_type_;
    int32_t num_reruns_;
    int32_t max_num_reruns_;
    int32_t log_limit_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ondewo_2fnlu_2foperation_5fmetadata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OperationMetadata

// .ondewo.nlu.OperationMetadata.Status status = 1;
inline void OperationMetadata::clear_status() {
  _impl_.status_ = 0;
}
inline ::ondewo::nlu::OperationMetadata_Status OperationMetadata::_internal_status() const {
  return static_cast< ::ondewo::nlu::OperationMetadata_Status >(_impl_.status_);
}
inline ::ondewo::nlu::OperationMetadata_Status OperationMetadata::status() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.status)
  return _internal_status();
}
inline void OperationMetadata::_internal_set_status(::ondewo::nlu::OperationMetadata_Status value) {
  
  _impl_.status_ = value;
}
inline void OperationMetadata::set_status(::ondewo::nlu::OperationMetadata_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.status)
}

// string parent_operation_name = 2;
inline void OperationMetadata::clear_parent_operation_name() {
  _impl_.parent_operation_name_.ClearToEmpty();
}
inline const std::string& OperationMetadata::parent_operation_name() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.parent_operation_name)
  return _internal_parent_operation_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OperationMetadata::set_parent_operation_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.parent_operation_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.parent_operation_name)
}
inline std::string* OperationMetadata::mutable_parent_operation_name() {
  std::string* _s = _internal_mutable_parent_operation_name();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.parent_operation_name)
  return _s;
}
inline const std::string& OperationMetadata::_internal_parent_operation_name() const {
  return _impl_.parent_operation_name_.Get();
}
inline void OperationMetadata::_internal_set_parent_operation_name(const std::string& value) {
  
  _impl_.parent_operation_name_.Set(value, GetArenaForAllocation());
}
inline std::string* OperationMetadata::_internal_mutable_parent_operation_name() {
  
  return _impl_.parent_operation_name_.Mutable(GetArenaForAllocation());
}
inline std::string* OperationMetadata::release_parent_operation_name() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.parent_operation_name)
  return _impl_.parent_operation_name_.Release();
}
inline void OperationMetadata::set_allocated_parent_operation_name(std::string* parent_operation_name) {
  if (parent_operation_name != nullptr) {
    
  } else {
    
  }
  _impl_.parent_operation_name_.SetAllocated(parent_operation_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.parent_operation_name_.IsDefault()) {
    _impl_.parent_operation_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.parent_operation_name)
}

// repeated string sub_operation_names = 3;
inline int OperationMetadata::_internal_sub_operation_names_size() const {
  return _impl_.sub_operation_names_.size();
}
inline int OperationMetadata::sub_operation_names_size() const {
  return _internal_sub_operation_names_size();
}
inline void OperationMetadata::clear_sub_operation_names() {
  _impl_.sub_operation_names_.Clear();
}
inline std::string* OperationMetadata::add_sub_operation_names() {
  std::string* _s = _internal_add_sub_operation_names();
  // @@protoc_insertion_point(field_add_mutable:ondewo.nlu.OperationMetadata.sub_operation_names)
  return _s;
}
inline const std::string& OperationMetadata::_internal_sub_operation_names(int index) const {
  return _impl_.sub_operation_names_.Get(index);
}
inline const std::string& OperationMetadata::sub_operation_names(int index) const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.sub_operation_names)
  return _internal_sub_operation_names(index);
}
inline std::string* OperationMetadata::mutable_sub_operation_names(int index) {
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.sub_operation_names)
  return _impl_.sub_operation_names_.Mutable(index);
}
inline void OperationMetadata::set_sub_operation_names(int index, const std::string& value) {
  _impl_.sub_operation_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.sub_operation_names)
}
inline void OperationMetadata::set_sub_operation_names(int index, std::string&& value) {
  _impl_.sub_operation_names_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.sub_operation_names)
}
inline void OperationMetadata::set_sub_operation_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.sub_operation_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ondewo.nlu.OperationMetadata.sub_operation_names)
}
inline void OperationMetadata::set_sub_operation_names(int index, const char* value, size_t size) {
  _impl_.sub_operation_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ondewo.nlu.OperationMetadata.sub_operation_names)
}
inline std::string* OperationMetadata::_internal_add_sub_operation_names() {
  return _impl_.sub_operation_names_.Add();
}
inline void OperationMetadata::add_sub_operation_names(const std::string& value) {
  _impl_.sub_operation_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ondewo.nlu.OperationMetadata.sub_operation_names)
}
inline void OperationMetadata::add_sub_operation_names(std::string&& value) {
  _impl_.sub_operation_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ondewo.nlu.OperationMetadata.sub_operation_names)
}
inline void OperationMetadata::add_sub_operation_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.sub_operation_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ondewo.nlu.OperationMetadata.sub_operation_names)
}
inline void OperationMetadata::add_sub_operation_names(const char* value, size_t size) {
  _impl_.sub_operation_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ondewo.nlu.OperationMetadata.sub_operation_names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
OperationMetadata::sub_operation_names() const {
  // @@protoc_insertion_point(field_list:ondewo.nlu.OperationMetadata.sub_operation_names)
  return _impl_.sub_operation_names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
OperationMetadata::mutable_sub_operation_names() {
  // @@protoc_insertion_point(field_mutable_list:ondewo.nlu.OperationMetadata.sub_operation_names)
  return &_impl_.sub_operation_names_;
}

// .google.protobuf.Timestamp create_time = 4;
inline bool OperationMetadata::_internal_has_create_time() const {
  return this != internal_default_instance() && _impl_.create_time_ != nullptr;
}
inline bool OperationMetadata::has_create_time() const {
  return _internal_has_create_time();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& OperationMetadata::_internal_create_time() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.create_time_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& OperationMetadata::create_time() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.create_time)
  return _internal_create_time();
}
inline void OperationMetadata::unsafe_arena_set_allocated_create_time(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* create_time) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.create_time_);
  }
  _impl_.create_time_ = create_time;
  if (create_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ondewo.nlu.OperationMetadata.create_time)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::release_create_time() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.create_time_;
  _impl_.create_time_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::unsafe_arena_release_create_time() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.create_time)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.create_time_;
  _impl_.create_time_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::_internal_mutable_create_time() {
  
  if (_impl_.create_time_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.create_time_ = p;
  }
  return _impl_.create_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::mutable_create_time() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_create_time();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.create_time)
  return _msg;
}
inline void OperationMetadata::set_allocated_create_time(::PROTOBUF_NAMESPACE_ID::Timestamp* create_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.create_time_);
  }
  if (create_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(create_time));
    if (message_arena != submessage_arena) {
      create_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, create_time, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.create_time_ = create_time;
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.create_time)
}

// .google.protobuf.Timestamp start_time = 5;
inline bool OperationMetadata::_internal_has_start_time() const {
  return this != internal_default_instance() && _impl_.start_time_ != nullptr;
}
inline bool OperationMetadata::has_start_time() const {
  return _internal_has_start_time();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& OperationMetadata::_internal_start_time() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.start_time_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& OperationMetadata::start_time() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.start_time)
  return _internal_start_time();
}
inline void OperationMetadata::unsafe_arena_set_allocated_start_time(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* start_time) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.start_time_);
  }
  _impl_.start_time_ = start_time;
  if (start_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ondewo.nlu.OperationMetadata.start_time)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::release_start_time() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.start_time_;
  _impl_.start_time_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::unsafe_arena_release_start_time() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.start_time)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.start_time_;
  _impl_.start_time_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::_internal_mutable_start_time() {
  
  if (_impl_.start_time_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.start_time_ = p;
  }
  return _impl_.start_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::mutable_start_time() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_start_time();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.start_time)
  return _msg;
}
inline void OperationMetadata::set_allocated_start_time(::PROTOBUF_NAMESPACE_ID::Timestamp* start_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.start_time_);
  }
  if (start_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(start_time));
    if (message_arena != submessage_arena) {
      start_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, start_time, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.start_time_ = start_time;
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.start_time)
}

// .google.protobuf.Timestamp end_time = 6;
inline bool OperationMetadata::_internal_has_end_time() const {
  return this != internal_default_instance() && _impl_.end_time_ != nullptr;
}
inline bool OperationMetadata::has_end_time() const {
  return _internal_has_end_time();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& OperationMetadata::_internal_end_time() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.end_time_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& OperationMetadata::end_time() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.end_time)
  return _internal_end_time();
}
inline void OperationMetadata::unsafe_arena_set_allocated_end_time(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* end_time) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.end_time_);
  }
  _impl_.end_time_ = end_time;
  if (end_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ondewo.nlu.OperationMetadata.end_time)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::release_end_time() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.end_time_;
  _impl_.end_time_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::unsafe_arena_release_end_time() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.end_time)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.end_time_;
  _impl_.end_time_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::_internal_mutable_end_time() {
  
  if (_impl_.end_time_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.end_time_ = p;
  }
  return _impl_.end_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::mutable_end_time() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_end_time();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.end_time)
  return _msg;
}
inline void OperationMetadata::set_allocated_end_time(::PROTOBUF_NAMESPACE_ID::Timestamp* end_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.end_time_);
  }
  if (end_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(end_time));
    if (message_arena != submessage_arena) {
      end_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, end_time, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.end_time_ = end_time;
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.end_time)
}

// bool is_cancellation_requested = 7;
inline void OperationMetadata::clear_is_cancellation_requested() {
  _impl_.is_cancellation_requested_ = false;
}
inline bool OperationMetadata::_internal_is_cancellation_requested() const {
  return _impl_.is_cancellation_requested_;
}
inline bool OperationMetadata::is_cancellation_requested() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.is_cancellation_requested)
  return _internal_is_cancellation_requested();
}
inline void OperationMetadata::_internal_set_is_cancellation_requested(bool value) {
  
  _impl_.is_cancellation_requested_ = value;
}
inline void OperationMetadata::set_is_cancellation_requested(bool value) {
  _internal_set_is_cancellation_requested(value);
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.is_cancellation_requested)
}

// string cancel_command = 8;
inline void OperationMetadata::clear_cancel_command() {
  _impl_.cancel_command_.ClearToEmpty();
}
inline const std::string& OperationMetadata::cancel_command() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.cancel_command)
  return _internal_cancel_command();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OperationMetadata::set_cancel_command(ArgT0&& arg0, ArgT... args) {
 
 _impl_.cancel_command_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.cancel_command)
}
inline std::string* OperationMetadata::mutable_cancel_command() {
  std::string* _s = _internal_mutable_cancel_command();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.cancel_command)
  return _s;
}
inline const std::string& OperationMetadata::_internal_cancel_command() const {
  return _impl_.cancel_command_.Get();
}
inline void OperationMetadata::_internal_set_cancel_command(const std::string& value) {
  
  _impl_.cancel_command_.Set(value, GetArenaForAllocation());
}
inline std::string* OperationMetadata::_internal_mutable_cancel_command() {
  
  return _impl_.cancel_command_.Mutable(GetArenaForAllocation());
}
inline std::string* OperationMetadata::release_cancel_command() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.cancel_command)
  return _impl_.cancel_command_.Release();
}
inline void OperationMetadata::set_allocated_cancel_command(std::string* cancel_command) {
  if (cancel_command != nullptr) {
    
  } else {
    
  }
  _impl_.cancel_command_.SetAllocated(cancel_command, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.cancel_command_.IsDefault()) {
    _impl_.cancel_command_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.cancel_command)
}

// string user_id_created = 9;
inline void OperationMetadata::clear_user_id_created() {
  _impl_.user_id_created_.ClearToEmpty();
}
inline const std::string& OperationMetadata::user_id_created() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.user_id_created)
  return _internal_user_id_created();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OperationMetadata::set_user_id_created(ArgT0&& arg0, ArgT... args) {
 
 _impl_.user_id_created_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.user_id_created)
}
inline std::string* OperationMetadata::mutable_user_id_created() {
  std::string* _s = _internal_mutable_user_id_created();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.user_id_created)
  return _s;
}
inline const std::string& OperationMetadata::_internal_user_id_created() const {
  return _impl_.user_id_created_.Get();
}
inline void OperationMetadata::_internal_set_user_id_created(const std::string& value) {
  
  _impl_.user_id_created_.Set(value, GetArenaForAllocation());
}
inline std::string* OperationMetadata::_internal_mutable_user_id_created() {
  
  return _impl_.user_id_created_.Mutable(GetArenaForAllocation());
}
inline std::string* OperationMetadata::release_user_id_created() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.user_id_created)
  return _impl_.user_id_created_.Release();
}
inline void OperationMetadata::set_allocated_user_id_created(std::string* user_id_created) {
  if (user_id_created != nullptr) {
    
  } else {
    
  }
  _impl_.user_id_created_.SetAllocated(user_id_created, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_id_created_.IsDefault()) {
    _impl_.user_id_created_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.user_id_created)
}

// string user_id_cancelled = 10;
inline void OperationMetadata::clear_user_id_cancelled() {
  _impl_.user_id_cancelled_.ClearToEmpty();
}
inline const std::string& OperationMetadata::user_id_cancelled() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.user_id_cancelled)
  return _internal_user_id_cancelled();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OperationMetadata::set_user_id_cancelled(ArgT0&& arg0, ArgT... args) {
 
 _impl_.user_id_cancelled_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.user_id_cancelled)
}
inline std::string* OperationMetadata::mutable_user_id_cancelled() {
  std::string* _s = _internal_mutable_user_id_cancelled();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.user_id_cancelled)
  return _s;
}
inline const std::string& OperationMetadata::_internal_user_id_cancelled() const {
  return _impl_.user_id_cancelled_.Get();
}
inline void OperationMetadata::_internal_set_user_id_cancelled(const std::string& value) {
  
  _impl_.user_id_cancelled_.Set(value, GetArenaForAllocation());
}
inline std::string* OperationMetadata::_internal_mutable_user_id_cancelled() {
  
  return _impl_.user_id_cancelled_.Mutable(GetArenaForAllocation());
}
inline std::string* OperationMetadata::release_user_id_cancelled() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.user_id_cancelled)
  return _impl_.user_id_cancelled_.Release();
}
inline void OperationMetadata::set_allocated_user_id_cancelled(std::string* user_id_cancelled) {
  if (user_id_cancelled != nullptr) {
    
  } else {
    
  }
  _impl_.user_id_cancelled_.SetAllocated(user_id_cancelled, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_id_cancelled_.IsDefault()) {
    _impl_.user_id_cancelled_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.user_id_cancelled)
}

// string project_parent = 11;
inline void OperationMetadata::clear_project_parent() {
  _impl_.project_parent_.ClearToEmpty();
}
inline const std::string& OperationMetadata::project_parent() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.project_parent)
  return _internal_project_parent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OperationMetadata::set_project_parent(ArgT0&& arg0, ArgT... args) {
 
 _impl_.project_parent_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.project_parent)
}
inline std::string* OperationMetadata::mutable_project_parent() {
  std::string* _s = _internal_mutable_project_parent();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.project_parent)
  return _s;
}
inline const std::string& OperationMetadata::_internal_project_parent() const {
  return _impl_.project_parent_.Get();
}
inline void OperationMetadata::_internal_set_project_parent(const std::string& value) {
  
  _impl_.project_parent_.Set(value, GetArenaForAllocation());
}
inline std::string* OperationMetadata::_internal_mutable_project_parent() {
  
  return _impl_.project_parent_.Mutable(GetArenaForAllocation());
}
inline std::string* OperationMetadata::release_project_parent() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.project_parent)
  return _impl_.project_parent_.Release();
}
inline void OperationMetadata::set_allocated_project_parent(std::string* project_parent) {
  if (project_parent != nullptr) {
    
  } else {
    
  }
  _impl_.project_parent_.SetAllocated(project_parent, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.project_parent_.IsDefault()) {
    _impl_.project_parent_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.project_parent)
}

// .ondewo.nlu.OperationMetadata.OperationType operation_type = 12;
inline void OperationMetadata::clear_operation_type() {
  _impl_.operation_type_ = 0;
}
inline ::ondewo::nlu::OperationMetadata_OperationType OperationMetadata::_internal_operation_type() const {
  return static_cast< ::ondewo::nlu::OperationMetadata_OperationType >(_impl_.operation_type_);
}
inline ::ondewo::nlu::OperationMetadata_OperationType OperationMetadata::operation_type() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.operation_type)
  return _internal_operation_type();
}
inline void OperationMetadata::_internal_set_operation_type(::ondewo::nlu::OperationMetadata_OperationType value) {
  
  _impl_.operation_type_ = value;
}
inline void OperationMetadata::set_operation_type(::ondewo::nlu::OperationMetadata_OperationType value) {
  _internal_set_operation_type(value);
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.operation_type)
}

// string host_name = 13;
inline void OperationMetadata::clear_host_name() {
  _impl_.host_name_.ClearToEmpty();
}
inline const std::string& OperationMetadata::host_name() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.host_name)
  return _internal_host_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OperationMetadata::set_host_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.host_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.host_name)
}
inline std::string* OperationMetadata::mutable_host_name() {
  std::string* _s = _internal_mutable_host_name();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.host_name)
  return _s;
}
inline const std::string& OperationMetadata::_internal_host_name() const {
  return _impl_.host_name_.Get();
}
inline void OperationMetadata::_internal_set_host_name(const std::string& value) {
  
  _impl_.host_name_.Set(value, GetArenaForAllocation());
}
inline std::string* OperationMetadata::_internal_mutable_host_name() {
  
  return _impl_.host_name_.Mutable(GetArenaForAllocation());
}
inline std::string* OperationMetadata::release_host_name() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.host_name)
  return _impl_.host_name_.Release();
}
inline void OperationMetadata::set_allocated_host_name(std::string* host_name) {
  if (host_name != nullptr) {
    
  } else {
    
  }
  _impl_.host_name_.SetAllocated(host_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.host_name_.IsDefault()) {
    _impl_.host_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.host_name)
}

// int32 num_reruns = 14;
inline void OperationMetadata::clear_num_reruns() {
  _impl_.num_reruns_ = 0;
}
inline int32_t OperationMetadata::_internal_num_reruns() const {
  return _impl_.num_reruns_;
}
inline int32_t OperationMetadata::num_reruns() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.num_reruns)
  return _internal_num_reruns();
}
inline void OperationMetadata::_internal_set_num_reruns(int32_t value) {
  
  _impl_.num_reruns_ = value;
}
inline void OperationMetadata::set_num_reruns(int32_t value) {
  _internal_set_num_reruns(value);
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.num_reruns)
}

// int32 max_num_reruns = 15;
inline void OperationMetadata::clear_max_num_reruns() {
  _impl_.max_num_reruns_ = 0;
}
inline int32_t OperationMetadata::_internal_max_num_reruns() const {
  return _impl_.max_num_reruns_;
}
inline int32_t OperationMetadata::max_num_reruns() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.max_num_reruns)
  return _internal_max_num_reruns();
}
inline void OperationMetadata::_internal_set_max_num_reruns(int32_t value) {
  
  _impl_.max_num_reruns_ = value;
}
inline void OperationMetadata::set_max_num_reruns(int32_t value) {
  _internal_set_max_num_reruns(value);
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.max_num_reruns)
}

// string description = 16;
inline void OperationMetadata::clear_description() {
  _impl_.description_.ClearToEmpty();
}
inline const std::string& OperationMetadata::description() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.description)
  return _internal_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OperationMetadata::set_description(ArgT0&& arg0, ArgT... args) {
 
 _impl_.description_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.description)
}
inline std::string* OperationMetadata::mutable_description() {
  std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.description)
  return _s;
}
inline const std::string& OperationMetadata::_internal_description() const {
  return _impl_.description_.Get();
}
inline void OperationMetadata::_internal_set_description(const std::string& value) {
  
  _impl_.description_.Set(value, GetArenaForAllocation());
}
inline std::string* OperationMetadata::_internal_mutable_description() {
  
  return _impl_.description_.Mutable(GetArenaForAllocation());
}
inline std::string* OperationMetadata::release_description() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.description)
  return _impl_.description_.Release();
}
inline void OperationMetadata::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  _impl_.description_.SetAllocated(description, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.description_.IsDefault()) {
    _impl_.description_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.description)
}

// repeated string log = 17;
inline int OperationMetadata::_internal_log_size() const {
  return _impl_.log_.size();
}
inline int OperationMetadata::log_size() const {
  return _internal_log_size();
}
inline void OperationMetadata::clear_log() {
  _impl_.log_.Clear();
}
inline std::string* OperationMetadata::add_log() {
  std::string* _s = _internal_add_log();
  // @@protoc_insertion_point(field_add_mutable:ondewo.nlu.OperationMetadata.log)
  return _s;
}
inline const std::string& OperationMetadata::_internal_log(int index) const {
  return _impl_.log_.Get(index);
}
inline const std::string& OperationMetadata::log(int index) const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.log)
  return _internal_log(index);
}
inline std::string* OperationMetadata::mutable_log(int index) {
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.log)
  return _impl_.log_.Mutable(index);
}
inline void OperationMetadata::set_log(int index, const std::string& value) {
  _impl_.log_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.log)
}
inline void OperationMetadata::set_log(int index, std::string&& value) {
  _impl_.log_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.log)
}
inline void OperationMetadata::set_log(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.log_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ondewo.nlu.OperationMetadata.log)
}
inline void OperationMetadata::set_log(int index, const char* value, size_t size) {
  _impl_.log_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ondewo.nlu.OperationMetadata.log)
}
inline std::string* OperationMetadata::_internal_add_log() {
  return _impl_.log_.Add();
}
inline void OperationMetadata::add_log(const std::string& value) {
  _impl_.log_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ondewo.nlu.OperationMetadata.log)
}
inline void OperationMetadata::add_log(std::string&& value) {
  _impl_.log_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:ondewo.nlu.OperationMetadata.log)
}
inline void OperationMetadata::add_log(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.log_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ondewo.nlu.OperationMetadata.log)
}
inline void OperationMetadata::add_log(const char* value, size_t size) {
  _impl_.log_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ondewo.nlu.OperationMetadata.log)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
OperationMetadata::log() const {
  // @@protoc_insertion_point(field_list:ondewo.nlu.OperationMetadata.log)
  return _impl_.log_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
OperationMetadata::mutable_log() {
  // @@protoc_insertion_point(field_mutable_list:ondewo.nlu.OperationMetadata.log)
  return &_impl_.log_;
}

// int32 log_limit = 18;
inline void OperationMetadata::clear_log_limit() {
  _impl_.log_limit_ = 0;
}
inline int32_t OperationMetadata::_internal_log_limit() const {
  return _impl_.log_limit_;
}
inline int32_t OperationMetadata::log_limit() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.log_limit)
  return _internal_log_limit();
}
inline void OperationMetadata::_internal_set_log_limit(int32_t value) {
  
  _impl_.log_limit_ = value;
}
inline void OperationMetadata::set_log_limit(int32_t value) {
  _internal_set_log_limit(value);
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.log_limit)
}

// .google.protobuf.Timestamp created_at = 19;
inline bool OperationMetadata::_internal_has_created_at() const {
  return this != internal_default_instance() && _impl_.created_at_ != nullptr;
}
inline bool OperationMetadata::has_created_at() const {
  return _internal_has_created_at();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& OperationMetadata::_internal_created_at() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.created_at_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& OperationMetadata::created_at() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.created_at)
  return _internal_created_at();
}
inline void OperationMetadata::unsafe_arena_set_allocated_created_at(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* created_at) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.created_at_);
  }
  _impl_.created_at_ = created_at;
  if (created_at) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ondewo.nlu.OperationMetadata.created_at)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::release_created_at() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.created_at_;
  _impl_.created_at_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::unsafe_arena_release_created_at() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.created_at)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.created_at_;
  _impl_.created_at_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::_internal_mutable_created_at() {
  
  if (_impl_.created_at_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.created_at_ = p;
  }
  return _impl_.created_at_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::mutable_created_at() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_created_at();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.created_at)
  return _msg;
}
inline void OperationMetadata::set_allocated_created_at(::PROTOBUF_NAMESPACE_ID::Timestamp* created_at) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.created_at_);
  }
  if (created_at) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(created_at));
    if (message_arena != submessage_arena) {
      created_at = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, created_at, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.created_at_ = created_at;
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.created_at)
}

// .google.protobuf.Timestamp modified_at = 20;
inline bool OperationMetadata::_internal_has_modified_at() const {
  return this != internal_default_instance() && _impl_.modified_at_ != nullptr;
}
inline bool OperationMetadata::has_modified_at() const {
  return _internal_has_modified_at();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& OperationMetadata::_internal_modified_at() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.modified_at_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& OperationMetadata::modified_at() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.modified_at)
  return _internal_modified_at();
}
inline void OperationMetadata::unsafe_arena_set_allocated_modified_at(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* modified_at) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.modified_at_);
  }
  _impl_.modified_at_ = modified_at;
  if (modified_at) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ondewo.nlu.OperationMetadata.modified_at)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::release_modified_at() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.modified_at_;
  _impl_.modified_at_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::unsafe_arena_release_modified_at() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.modified_at)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.modified_at_;
  _impl_.modified_at_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::_internal_mutable_modified_at() {
  
  if (_impl_.modified_at_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.modified_at_ = p;
  }
  return _impl_.modified_at_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* OperationMetadata::mutable_modified_at() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_modified_at();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.modified_at)
  return _msg;
}
inline void OperationMetadata::set_allocated_modified_at(::PROTOBUF_NAMESPACE_ID::Timestamp* modified_at) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.modified_at_);
  }
  if (modified_at) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(modified_at));
    if (message_arena != submessage_arena) {
      modified_at = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, modified_at, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.modified_at_ = modified_at;
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.modified_at)
}

// string created_by = 21;
inline void OperationMetadata::clear_created_by() {
  _impl_.created_by_.ClearToEmpty();
}
inline const std::string& OperationMetadata::created_by() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.created_by)
  return _internal_created_by();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OperationMetadata::set_created_by(ArgT0&& arg0, ArgT... args) {
 
 _impl_.created_by_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.created_by)
}
inline std::string* OperationMetadata::mutable_created_by() {
  std::string* _s = _internal_mutable_created_by();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.created_by)
  return _s;
}
inline const std::string& OperationMetadata::_internal_created_by() const {
  return _impl_.created_by_.Get();
}
inline void OperationMetadata::_internal_set_created_by(const std::string& value) {
  
  _impl_.created_by_.Set(value, GetArenaForAllocation());
}
inline std::string* OperationMetadata::_internal_mutable_created_by() {
  
  return _impl_.created_by_.Mutable(GetArenaForAllocation());
}
inline std::string* OperationMetadata::release_created_by() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.created_by)
  return _impl_.created_by_.Release();
}
inline void OperationMetadata::set_allocated_created_by(std::string* created_by) {
  if (created_by != nullptr) {
    
  } else {
    
  }
  _impl_.created_by_.SetAllocated(created_by, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.created_by_.IsDefault()) {
    _impl_.created_by_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.created_by)
}

// string modified_by = 22;
inline void OperationMetadata::clear_modified_by() {
  _impl_.modified_by_.ClearToEmpty();
}
inline const std::string& OperationMetadata::modified_by() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.OperationMetadata.modified_by)
  return _internal_modified_by();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void OperationMetadata::set_modified_by(ArgT0&& arg0, ArgT... args) {
 
 _impl_.modified_by_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.OperationMetadata.modified_by)
}
inline std::string* OperationMetadata::mutable_modified_by() {
  std::string* _s = _internal_mutable_modified_by();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.OperationMetadata.modified_by)
  return _s;
}
inline const std::string& OperationMetadata::_internal_modified_by() const {
  return _impl_.modified_by_.Get();
}
inline void OperationMetadata::_internal_set_modified_by(const std::string& value) {
  
  _impl_.modified_by_.Set(value, GetArenaForAllocation());
}
inline std::string* OperationMetadata::_internal_mutable_modified_by() {
  
  return _impl_.modified_by_.Mutable(GetArenaForAllocation());
}
inline std::string* OperationMetadata::release_modified_by() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.OperationMetadata.modified_by)
  return _impl_.modified_by_.Release();
}
inline void OperationMetadata::set_allocated_modified_by(std::string* modified_by) {
  if (modified_by != nullptr) {
    
  } else {
    
  }
  _impl_.modified_by_.SetAllocated(modified_by, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.modified_by_.IsDefault()) {
    _impl_.modified_by_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.OperationMetadata.modified_by)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace nlu
}  // namespace ondewo

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ondewo::nlu::OperationMetadata_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ondewo::nlu::OperationMetadata_Status>() {
  return ::ondewo::nlu::OperationMetadata_Status_descriptor();
}
template <> struct is_proto_enum< ::ondewo::nlu::OperationMetadata_OperationType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ondewo::nlu::OperationMetadata_OperationType>() {
  return ::ondewo::nlu::OperationMetadata_OperationType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ondewo_2fnlu_2foperation_5fmetadata_2eproto
