// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ondewo/nlu/project_statistics.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ondewo_2fnlu_2fproject_5fstatistics_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ondewo_2fnlu_2fproject_5fstatistics_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "google/api/annotations.pb.h"
#include "ondewo/nlu/intent.pb.h"
#include "ondewo/nlu/common.pb.h"
#include "ondewo/nlu/entity_type.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ondewo_2fnlu_2fproject_5fstatistics_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ondewo_2fnlu_2fproject_5fstatistics_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ondewo_2fnlu_2fproject_5fstatistics_2eproto;
namespace ondewo {
namespace nlu {
class GetEntityTypeCountRequest;
struct GetEntityTypeCountRequestDefaultTypeInternal;
extern GetEntityTypeCountRequestDefaultTypeInternal _GetEntityTypeCountRequest_default_instance_;
class GetIntentCountRequest;
struct GetIntentCountRequestDefaultTypeInternal;
extern GetIntentCountRequestDefaultTypeInternal _GetIntentCountRequest_default_instance_;
class GetProjectElementStatRequest;
struct GetProjectElementStatRequestDefaultTypeInternal;
extern GetProjectElementStatRequestDefaultTypeInternal _GetProjectElementStatRequest_default_instance_;
class GetProjectStatRequest;
struct GetProjectStatRequestDefaultTypeInternal;
extern GetProjectStatRequestDefaultTypeInternal _GetProjectStatRequest_default_instance_;
}  // namespace nlu
}  // namespace ondewo
PROTOBUF_NAMESPACE_OPEN
template<> ::ondewo::nlu::GetEntityTypeCountRequest* Arena::CreateMaybeMessage<::ondewo::nlu::GetEntityTypeCountRequest>(Arena*);
template<> ::ondewo::nlu::GetIntentCountRequest* Arena::CreateMaybeMessage<::ondewo::nlu::GetIntentCountRequest>(Arena*);
template<> ::ondewo::nlu::GetProjectElementStatRequest* Arena::CreateMaybeMessage<::ondewo::nlu::GetProjectElementStatRequest>(Arena*);
template<> ::ondewo::nlu::GetProjectStatRequest* Arena::CreateMaybeMessage<::ondewo::nlu::GetProjectStatRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ondewo {
namespace nlu {

// ===================================================================

class GetIntentCountRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ondewo.nlu.GetIntentCountRequest) */ {
 public:
  inline GetIntentCountRequest() : GetIntentCountRequest(nullptr) {}
  ~GetIntentCountRequest() override;
  explicit PROTOBUF_CONSTEXPR GetIntentCountRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetIntentCountRequest(const GetIntentCountRequest& from);
  GetIntentCountRequest(GetIntentCountRequest&& from) noexcept
    : GetIntentCountRequest() {
    *this = ::std::move(from);
  }

  inline GetIntentCountRequest& operator=(const GetIntentCountRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetIntentCountRequest& operator=(GetIntentCountRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetIntentCountRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetIntentCountRequest* internal_default_instance() {
    return reinterpret_cast<const GetIntentCountRequest*>(
               &_GetIntentCountRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GetIntentCountRequest& a, GetIntentCountRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetIntentCountRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetIntentCountRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetIntentCountRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetIntentCountRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetIntentCountRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetIntentCountRequest& from) {
    GetIntentCountRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetIntentCountRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ondewo.nlu.GetIntentCountRequest";
  }
  protected:
  explicit GetIntentCountRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParentFieldNumber = 1,
    kFilterByCategoryFieldNumber = 2,
  };
  // string parent = 1;
  void clear_parent();
  const std::string& parent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_parent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_parent();
  PROTOBUF_NODISCARD std::string* release_parent();
  void set_allocated_parent(std::string* parent);
  private:
  const std::string& _internal_parent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_parent(const std::string& value);
  std::string* _internal_mutable_parent();
  public:

  // .ondewo.nlu.IntentCategory filter_by_category = 2;
  void clear_filter_by_category();
  ::ondewo::nlu::IntentCategory filter_by_category() const;
  void set_filter_by_category(::ondewo::nlu::IntentCategory value);
  private:
  ::ondewo::nlu::IntentCategory _internal_filter_by_category() const;
  void _internal_set_filter_by_category(::ondewo::nlu::IntentCategory value);
  public:

  // @@protoc_insertion_point(class_scope:ondewo.nlu.GetIntentCountRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr parent_;
    int filter_by_category_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ondewo_2fnlu_2fproject_5fstatistics_2eproto;
};
// -------------------------------------------------------------------

class GetEntityTypeCountRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ondewo.nlu.GetEntityTypeCountRequest) */ {
 public:
  inline GetEntityTypeCountRequest() : GetEntityTypeCountRequest(nullptr) {}
  ~GetEntityTypeCountRequest() override;
  explicit PROTOBUF_CONSTEXPR GetEntityTypeCountRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetEntityTypeCountRequest(const GetEntityTypeCountRequest& from);
  GetEntityTypeCountRequest(GetEntityTypeCountRequest&& from) noexcept
    : GetEntityTypeCountRequest() {
    *this = ::std::move(from);
  }

  inline GetEntityTypeCountRequest& operator=(const GetEntityTypeCountRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetEntityTypeCountRequest& operator=(GetEntityTypeCountRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetEntityTypeCountRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetEntityTypeCountRequest* internal_default_instance() {
    return reinterpret_cast<const GetEntityTypeCountRequest*>(
               &_GetEntityTypeCountRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetEntityTypeCountRequest& a, GetEntityTypeCountRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetEntityTypeCountRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetEntityTypeCountRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetEntityTypeCountRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetEntityTypeCountRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetEntityTypeCountRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetEntityTypeCountRequest& from) {
    GetEntityTypeCountRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetEntityTypeCountRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ondewo.nlu.GetEntityTypeCountRequest";
  }
  protected:
  explicit GetEntityTypeCountRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParentFieldNumber = 1,
    kFilterByCategoryFieldNumber = 2,
  };
  // string parent = 1;
  void clear_parent();
  const std::string& parent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_parent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_parent();
  PROTOBUF_NODISCARD std::string* release_parent();
  void set_allocated_parent(std::string* parent);
  private:
  const std::string& _internal_parent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_parent(const std::string& value);
  std::string* _internal_mutable_parent();
  public:

  // .ondewo.nlu.EntityTypeCategory filter_by_category = 2;
  void clear_filter_by_category();
  ::ondewo::nlu::EntityTypeCategory filter_by_category() const;
  void set_filter_by_category(::ondewo::nlu::EntityTypeCategory value);
  private:
  ::ondewo::nlu::EntityTypeCategory _internal_filter_by_category() const;
  void _internal_set_filter_by_category(::ondewo::nlu::EntityTypeCategory value);
  public:

  // @@protoc_insertion_point(class_scope:ondewo.nlu.GetEntityTypeCountRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr parent_;
    int filter_by_category_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ondewo_2fnlu_2fproject_5fstatistics_2eproto;
};
// -------------------------------------------------------------------

class GetProjectStatRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ondewo.nlu.GetProjectStatRequest) */ {
 public:
  inline GetProjectStatRequest() : GetProjectStatRequest(nullptr) {}
  ~GetProjectStatRequest() override;
  explicit PROTOBUF_CONSTEXPR GetProjectStatRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetProjectStatRequest(const GetProjectStatRequest& from);
  GetProjectStatRequest(GetProjectStatRequest&& from) noexcept
    : GetProjectStatRequest() {
    *this = ::std::move(from);
  }

  inline GetProjectStatRequest& operator=(const GetProjectStatRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetProjectStatRequest& operator=(GetProjectStatRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetProjectStatRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetProjectStatRequest* internal_default_instance() {
    return reinterpret_cast<const GetProjectStatRequest*>(
               &_GetProjectStatRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetProjectStatRequest& a, GetProjectStatRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetProjectStatRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetProjectStatRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetProjectStatRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetProjectStatRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetProjectStatRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetProjectStatRequest& from) {
    GetProjectStatRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetProjectStatRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ondewo.nlu.GetProjectStatRequest";
  }
  protected:
  explicit GetProjectStatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParentFieldNumber = 1,
  };
  // string parent = 1;
  void clear_parent();
  const std::string& parent() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_parent(ArgT0&& arg0, ArgT... args);
  std::string* mutable_parent();
  PROTOBUF_NODISCARD std::string* release_parent();
  void set_allocated_parent(std::string* parent);
  private:
  const std::string& _internal_parent() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_parent(const std::string& value);
  std::string* _internal_mutable_parent();
  public:

  // @@protoc_insertion_point(class_scope:ondewo.nlu.GetProjectStatRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr parent_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ondewo_2fnlu_2fproject_5fstatistics_2eproto;
};
// -------------------------------------------------------------------

class GetProjectElementStatRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ondewo.nlu.GetProjectElementStatRequest) */ {
 public:
  inline GetProjectElementStatRequest() : GetProjectElementStatRequest(nullptr) {}
  ~GetProjectElementStatRequest() override;
  explicit PROTOBUF_CONSTEXPR GetProjectElementStatRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetProjectElementStatRequest(const GetProjectElementStatRequest& from);
  GetProjectElementStatRequest(GetProjectElementStatRequest&& from) noexcept
    : GetProjectElementStatRequest() {
    *this = ::std::move(from);
  }

  inline GetProjectElementStatRequest& operator=(const GetProjectElementStatRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetProjectElementStatRequest& operator=(GetProjectElementStatRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetProjectElementStatRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetProjectElementStatRequest* internal_default_instance() {
    return reinterpret_cast<const GetProjectElementStatRequest*>(
               &_GetProjectElementStatRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(GetProjectElementStatRequest& a, GetProjectElementStatRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetProjectElementStatRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetProjectElementStatRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetProjectElementStatRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetProjectElementStatRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetProjectElementStatRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetProjectElementStatRequest& from) {
    GetProjectElementStatRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetProjectElementStatRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ondewo.nlu.GetProjectElementStatRequest";
  }
  protected:
  explicit GetProjectElementStatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kLanguageCodeFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string language_code = 2;
  void clear_language_code();
  const std::string& language_code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_language_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_language_code();
  PROTOBUF_NODISCARD std::string* release_language_code();
  void set_allocated_language_code(std::string* language_code);
  private:
  const std::string& _internal_language_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_language_code(const std::string& value);
  std::string* _internal_mutable_language_code();
  public:

  // @@protoc_insertion_point(class_scope:ondewo.nlu.GetProjectElementStatRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr language_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ondewo_2fnlu_2fproject_5fstatistics_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetIntentCountRequest

// string parent = 1;
inline void GetIntentCountRequest::clear_parent() {
  _impl_.parent_.ClearToEmpty();
}
inline const std::string& GetIntentCountRequest::parent() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.GetIntentCountRequest.parent)
  return _internal_parent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetIntentCountRequest::set_parent(ArgT0&& arg0, ArgT... args) {
 
 _impl_.parent_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.GetIntentCountRequest.parent)
}
inline std::string* GetIntentCountRequest::mutable_parent() {
  std::string* _s = _internal_mutable_parent();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.GetIntentCountRequest.parent)
  return _s;
}
inline const std::string& GetIntentCountRequest::_internal_parent() const {
  return _impl_.parent_.Get();
}
inline void GetIntentCountRequest::_internal_set_parent(const std::string& value) {
  
  _impl_.parent_.Set(value, GetArenaForAllocation());
}
inline std::string* GetIntentCountRequest::_internal_mutable_parent() {
  
  return _impl_.parent_.Mutable(GetArenaForAllocation());
}
inline std::string* GetIntentCountRequest::release_parent() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.GetIntentCountRequest.parent)
  return _impl_.parent_.Release();
}
inline void GetIntentCountRequest::set_allocated_parent(std::string* parent) {
  if (parent != nullptr) {
    
  } else {
    
  }
  _impl_.parent_.SetAllocated(parent, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.parent_.IsDefault()) {
    _impl_.parent_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.GetIntentCountRequest.parent)
}

// .ondewo.nlu.IntentCategory filter_by_category = 2;
inline void GetIntentCountRequest::clear_filter_by_category() {
  _impl_.filter_by_category_ = 0;
}
inline ::ondewo::nlu::IntentCategory GetIntentCountRequest::_internal_filter_by_category() const {
  return static_cast< ::ondewo::nlu::IntentCategory >(_impl_.filter_by_category_);
}
inline ::ondewo::nlu::IntentCategory GetIntentCountRequest::filter_by_category() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.GetIntentCountRequest.filter_by_category)
  return _internal_filter_by_category();
}
inline void GetIntentCountRequest::_internal_set_filter_by_category(::ondewo::nlu::IntentCategory value) {
  
  _impl_.filter_by_category_ = value;
}
inline void GetIntentCountRequest::set_filter_by_category(::ondewo::nlu::IntentCategory value) {
  _internal_set_filter_by_category(value);
  // @@protoc_insertion_point(field_set:ondewo.nlu.GetIntentCountRequest.filter_by_category)
}

// -------------------------------------------------------------------

// GetEntityTypeCountRequest

// string parent = 1;
inline void GetEntityTypeCountRequest::clear_parent() {
  _impl_.parent_.ClearToEmpty();
}
inline const std::string& GetEntityTypeCountRequest::parent() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.GetEntityTypeCountRequest.parent)
  return _internal_parent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetEntityTypeCountRequest::set_parent(ArgT0&& arg0, ArgT... args) {
 
 _impl_.parent_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.GetEntityTypeCountRequest.parent)
}
inline std::string* GetEntityTypeCountRequest::mutable_parent() {
  std::string* _s = _internal_mutable_parent();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.GetEntityTypeCountRequest.parent)
  return _s;
}
inline const std::string& GetEntityTypeCountRequest::_internal_parent() const {
  return _impl_.parent_.Get();
}
inline void GetEntityTypeCountRequest::_internal_set_parent(const std::string& value) {
  
  _impl_.parent_.Set(value, GetArenaForAllocation());
}
inline std::string* GetEntityTypeCountRequest::_internal_mutable_parent() {
  
  return _impl_.parent_.Mutable(GetArenaForAllocation());
}
inline std::string* GetEntityTypeCountRequest::release_parent() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.GetEntityTypeCountRequest.parent)
  return _impl_.parent_.Release();
}
inline void GetEntityTypeCountRequest::set_allocated_parent(std::string* parent) {
  if (parent != nullptr) {
    
  } else {
    
  }
  _impl_.parent_.SetAllocated(parent, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.parent_.IsDefault()) {
    _impl_.parent_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.GetEntityTypeCountRequest.parent)
}

// .ondewo.nlu.EntityTypeCategory filter_by_category = 2;
inline void GetEntityTypeCountRequest::clear_filter_by_category() {
  _impl_.filter_by_category_ = 0;
}
inline ::ondewo::nlu::EntityTypeCategory GetEntityTypeCountRequest::_internal_filter_by_category() const {
  return static_cast< ::ondewo::nlu::EntityTypeCategory >(_impl_.filter_by_category_);
}
inline ::ondewo::nlu::EntityTypeCategory GetEntityTypeCountRequest::filter_by_category() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.GetEntityTypeCountRequest.filter_by_category)
  return _internal_filter_by_category();
}
inline void GetEntityTypeCountRequest::_internal_set_filter_by_category(::ondewo::nlu::EntityTypeCategory value) {
  
  _impl_.filter_by_category_ = value;
}
inline void GetEntityTypeCountRequest::set_filter_by_category(::ondewo::nlu::EntityTypeCategory value) {
  _internal_set_filter_by_category(value);
  // @@protoc_insertion_point(field_set:ondewo.nlu.GetEntityTypeCountRequest.filter_by_category)
}

// -------------------------------------------------------------------

// GetProjectStatRequest

// string parent = 1;
inline void GetProjectStatRequest::clear_parent() {
  _impl_.parent_.ClearToEmpty();
}
inline const std::string& GetProjectStatRequest::parent() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.GetProjectStatRequest.parent)
  return _internal_parent();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetProjectStatRequest::set_parent(ArgT0&& arg0, ArgT... args) {
 
 _impl_.parent_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.GetProjectStatRequest.parent)
}
inline std::string* GetProjectStatRequest::mutable_parent() {
  std::string* _s = _internal_mutable_parent();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.GetProjectStatRequest.parent)
  return _s;
}
inline const std::string& GetProjectStatRequest::_internal_parent() const {
  return _impl_.parent_.Get();
}
inline void GetProjectStatRequest::_internal_set_parent(const std::string& value) {
  
  _impl_.parent_.Set(value, GetArenaForAllocation());
}
inline std::string* GetProjectStatRequest::_internal_mutable_parent() {
  
  return _impl_.parent_.Mutable(GetArenaForAllocation());
}
inline std::string* GetProjectStatRequest::release_parent() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.GetProjectStatRequest.parent)
  return _impl_.parent_.Release();
}
inline void GetProjectStatRequest::set_allocated_parent(std::string* parent) {
  if (parent != nullptr) {
    
  } else {
    
  }
  _impl_.parent_.SetAllocated(parent, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.parent_.IsDefault()) {
    _impl_.parent_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.GetProjectStatRequest.parent)
}

// -------------------------------------------------------------------

// GetProjectElementStatRequest

// string name = 1;
inline void GetProjectElementStatRequest::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& GetProjectElementStatRequest::name() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.GetProjectElementStatRequest.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetProjectElementStatRequest::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.GetProjectElementStatRequest.name)
}
inline std::string* GetProjectElementStatRequest::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.GetProjectElementStatRequest.name)
  return _s;
}
inline const std::string& GetProjectElementStatRequest::_internal_name() const {
  return _impl_.name_.Get();
}
inline void GetProjectElementStatRequest::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* GetProjectElementStatRequest::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* GetProjectElementStatRequest::release_name() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.GetProjectElementStatRequest.name)
  return _impl_.name_.Release();
}
inline void GetProjectElementStatRequest::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.GetProjectElementStatRequest.name)
}

// string language_code = 2;
inline void GetProjectElementStatRequest::clear_language_code() {
  _impl_.language_code_.ClearToEmpty();
}
inline const std::string& GetProjectElementStatRequest::language_code() const {
  // @@protoc_insertion_point(field_get:ondewo.nlu.GetProjectElementStatRequest.language_code)
  return _internal_language_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetProjectElementStatRequest::set_language_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.language_code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ondewo.nlu.GetProjectElementStatRequest.language_code)
}
inline std::string* GetProjectElementStatRequest::mutable_language_code() {
  std::string* _s = _internal_mutable_language_code();
  // @@protoc_insertion_point(field_mutable:ondewo.nlu.GetProjectElementStatRequest.language_code)
  return _s;
}
inline const std::string& GetProjectElementStatRequest::_internal_language_code() const {
  return _impl_.language_code_.Get();
}
inline void GetProjectElementStatRequest::_internal_set_language_code(const std::string& value) {
  
  _impl_.language_code_.Set(value, GetArenaForAllocation());
}
inline std::string* GetProjectElementStatRequest::_internal_mutable_language_code() {
  
  return _impl_.language_code_.Mutable(GetArenaForAllocation());
}
inline std::string* GetProjectElementStatRequest::release_language_code() {
  // @@protoc_insertion_point(field_release:ondewo.nlu.GetProjectElementStatRequest.language_code)
  return _impl_.language_code_.Release();
}
inline void GetProjectElementStatRequest::set_allocated_language_code(std::string* language_code) {
  if (language_code != nullptr) {
    
  } else {
    
  }
  _impl_.language_code_.SetAllocated(language_code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.language_code_.IsDefault()) {
    _impl_.language_code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ondewo.nlu.GetProjectElementStatRequest.language_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace nlu
}  // namespace ondewo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ondewo_2fnlu_2fproject_5fstatistics_2eproto
