// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ondewo/nlu/server_statistics.proto
// Original file comments:
// Copyright 2020-2026 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_ondewo_2fnlu_2fserver_5fstatistics_2eproto__INCLUDED
#define GRPC_ondewo_2fnlu_2fserver_5fstatistics_2eproto__INCLUDED

#include "ondewo/nlu/server_statistics.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace ondewo {
namespace nlu {

// Server project statistics
class ServerStatistics final {
 public:
  static constexpr char const* service_full_name() {
    return "ondewo.nlu.ServerStatistics";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Returns the count of projects in the CAI server
    virtual ::grpc::Status GetProjectCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::ondewo::nlu::StatResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>> AsyncGetProjectCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>>(AsyncGetProjectCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>> PrepareAsyncGetProjectCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>>(PrepareAsyncGetProjectCountRaw(context, request, cq));
    }
    // Returns the count of projects of a user
    virtual ::grpc::Status GetUserProjectCount(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest& request, ::ondewo::nlu::StatResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>> AsyncGetUserProjectCount(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>>(AsyncGetUserProjectCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>> PrepareAsyncGetUserProjectCount(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>>(PrepareAsyncGetUserProjectCountRaw(context, request, cq));
    }
    // Returns the users count within a project
    virtual ::grpc::Status GetUserCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::ondewo::nlu::StatResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>> AsyncGetUserCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>>(AsyncGetUserCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>> PrepareAsyncGetUserCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>>(PrepareAsyncGetUserCountRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Returns the count of projects in the CAI server
      virtual void GetProjectCount(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetProjectCount(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Returns the count of projects of a user
      virtual void GetUserProjectCount(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest* request, ::ondewo::nlu::StatResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetUserProjectCount(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest* request, ::ondewo::nlu::StatResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Returns the users count within a project
      virtual void GetUserCount(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetUserCount(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>* AsyncGetProjectCountRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>* PrepareAsyncGetProjectCountRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>* AsyncGetUserProjectCountRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>* PrepareAsyncGetUserProjectCountRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>* AsyncGetUserCountRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ondewo::nlu::StatResponse>* PrepareAsyncGetUserCountRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetProjectCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::ondewo::nlu::StatResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>> AsyncGetProjectCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>>(AsyncGetProjectCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>> PrepareAsyncGetProjectCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>>(PrepareAsyncGetProjectCountRaw(context, request, cq));
    }
    ::grpc::Status GetUserProjectCount(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest& request, ::ondewo::nlu::StatResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>> AsyncGetUserProjectCount(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>>(AsyncGetUserProjectCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>> PrepareAsyncGetUserProjectCount(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>>(PrepareAsyncGetUserProjectCountRaw(context, request, cq));
    }
    ::grpc::Status GetUserCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::ondewo::nlu::StatResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>> AsyncGetUserCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>>(AsyncGetUserCountRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>> PrepareAsyncGetUserCount(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>>(PrepareAsyncGetUserCountRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetProjectCount(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response, std::function<void(::grpc::Status)>) override;
      void GetProjectCount(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetUserProjectCount(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest* request, ::ondewo::nlu::StatResponse* response, std::function<void(::grpc::Status)>) override;
      void GetUserProjectCount(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest* request, ::ondewo::nlu::StatResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetUserCount(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response, std::function<void(::grpc::Status)>) override;
      void GetUserCount(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>* AsyncGetProjectCountRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>* PrepareAsyncGetProjectCountRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>* AsyncGetUserProjectCountRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>* PrepareAsyncGetUserProjectCountRaw(::grpc::ClientContext* context, const ::ondewo::nlu::GetUserProjectCountRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>* AsyncGetUserCountRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ondewo::nlu::StatResponse>* PrepareAsyncGetUserCountRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetProjectCount_;
    const ::grpc::internal::RpcMethod rpcmethod_GetUserProjectCount_;
    const ::grpc::internal::RpcMethod rpcmethod_GetUserCount_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Returns the count of projects in the CAI server
    virtual ::grpc::Status GetProjectCount(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response);
    // Returns the count of projects of a user
    virtual ::grpc::Status GetUserProjectCount(::grpc::ServerContext* context, const ::ondewo::nlu::GetUserProjectCountRequest* request, ::ondewo::nlu::StatResponse* response);
    // Returns the users count within a project
    virtual ::grpc::Status GetUserCount(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetProjectCount() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetProjectCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetProjectCount(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::nlu::StatResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUserProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUserProjectCount() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetUserProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserProjectCount(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetUserProjectCountRequest* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserProjectCount(::grpc::ServerContext* context, ::ondewo::nlu::GetUserProjectCountRequest* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::nlu::StatResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUserCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUserCount() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetUserCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserCount(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::ondewo::nlu::StatResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetProjectCount<WithAsyncMethod_GetUserProjectCount<WithAsyncMethod_GetUserCount<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetProjectCount() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::ondewo::nlu::StatResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response) { return this->GetProjectCount(context, request, response); }));}
    void SetMessageAllocatorFor_GetProjectCount(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::ondewo::nlu::StatResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::ondewo::nlu::StatResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetProjectCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetProjectCount(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetUserProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetUserProjectCount() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::GetUserProjectCountRequest, ::ondewo::nlu::StatResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ondewo::nlu::GetUserProjectCountRequest* request, ::ondewo::nlu::StatResponse* response) { return this->GetUserProjectCount(context, request, response); }));}
    void SetMessageAllocatorFor_GetUserProjectCount(
        ::grpc::MessageAllocator< ::ondewo::nlu::GetUserProjectCountRequest, ::ondewo::nlu::StatResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ondewo::nlu::GetUserProjectCountRequest, ::ondewo::nlu::StatResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetUserProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserProjectCount(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetUserProjectCountRequest* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserProjectCount(
      ::grpc::CallbackServerContext* /*context*/, const ::ondewo::nlu::GetUserProjectCountRequest* /*request*/, ::ondewo::nlu::StatResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetUserCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetUserCount() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::ondewo::nlu::StatResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::ondewo::nlu::StatResponse* response) { return this->GetUserCount(context, request, response); }));}
    void SetMessageAllocatorFor_GetUserCount(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::ondewo::nlu::StatResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::ondewo::nlu::StatResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetUserCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserCount(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetProjectCount<WithCallbackMethod_GetUserProjectCount<WithCallbackMethod_GetUserCount<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetProjectCount() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetProjectCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetUserProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUserProjectCount() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetUserProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserProjectCount(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetUserProjectCountRequest* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetUserCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUserCount() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetUserCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetProjectCount() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetProjectCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetProjectCount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUserProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUserProjectCount() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetUserProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserProjectCount(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetUserProjectCountRequest* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserProjectCount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUserCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUserCount() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetUserCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUserCount(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetProjectCount() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetProjectCount(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetProjectCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetProjectCount(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetUserProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetUserProjectCount() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetUserProjectCount(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetUserProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserProjectCount(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetUserProjectCountRequest* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserProjectCount(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetUserCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetUserCount() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetUserCount(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetUserCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUserCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetUserCount(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetProjectCount() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::ondewo::nlu::StatResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::ondewo::nlu::StatResponse>* streamer) {
                       return this->StreamedGetProjectCount(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetProjectCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetProjectCount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::ondewo::nlu::StatResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUserProjectCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetUserProjectCount() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ondewo::nlu::GetUserProjectCountRequest, ::ondewo::nlu::StatResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ondewo::nlu::GetUserProjectCountRequest, ::ondewo::nlu::StatResponse>* streamer) {
                       return this->StreamedGetUserProjectCount(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetUserProjectCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUserProjectCount(::grpc::ServerContext* /*context*/, const ::ondewo::nlu::GetUserProjectCountRequest* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUserProjectCount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ondewo::nlu::GetUserProjectCountRequest,::ondewo::nlu::StatResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUserCount : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetUserCount() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::ondewo::nlu::StatResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::ondewo::nlu::StatResponse>* streamer) {
                       return this->StreamedGetUserCount(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetUserCount() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUserCount(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::ondewo::nlu::StatResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUserCount(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::ondewo::nlu::StatResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetProjectCount<WithStreamedUnaryMethod_GetUserProjectCount<WithStreamedUnaryMethod_GetUserCount<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetProjectCount<WithStreamedUnaryMethod_GetUserProjectCount<WithStreamedUnaryMethod_GetUserCount<Service > > > StreamedService;
};

}  // namespace nlu
}  // namespace ondewo


#endif  // GRPC_ondewo_2fnlu_2fserver_5fstatistics_2eproto__INCLUDED
