// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ondewo/nlu/utility.proto

#include "ondewo/nlu/utility.pb.h"
#include "ondewo/nlu/utility.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ondewo {
namespace nlu {

static const char* Utilities_method_names[] = {
  "/ondewo.nlu.Utilities/ValidateRegex",
  "/ondewo.nlu.Utilities/ValidateEmbeddedRegex",
  "/ondewo.nlu.Utilities/CleanAllIntents",
  "/ondewo.nlu.Utilities/CleanIntent",
  "/ondewo.nlu.Utilities/CleanAllEntityTypes",
  "/ondewo.nlu.Utilities/CleanEntityType",
  "/ondewo.nlu.Utilities/AddTrainingPhrases",
  "/ondewo.nlu.Utilities/AddTrainingPhrasesFromCSV",
};

std::unique_ptr< Utilities::Stub> Utilities::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Utilities::Stub> stub(new Utilities::Stub(channel, options));
  return stub;
}

Utilities::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ValidateRegex_(Utilities_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ValidateEmbeddedRegex_(Utilities_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CleanAllIntents_(Utilities_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CleanIntent_(Utilities_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CleanAllEntityTypes_(Utilities_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CleanEntityType_(Utilities_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddTrainingPhrases_(Utilities_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddTrainingPhrasesFromCSV_(Utilities_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Utilities::Stub::ValidateRegex(::grpc::ClientContext* context, const ::ondewo::nlu::ValidateRegexRequest& request, ::ondewo::nlu::ValidateRegexResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::ValidateRegexRequest, ::ondewo::nlu::ValidateRegexResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ValidateRegex_, context, request, response);
}

void Utilities::Stub::async::ValidateRegex(::grpc::ClientContext* context, const ::ondewo::nlu::ValidateRegexRequest* request, ::ondewo::nlu::ValidateRegexResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::ValidateRegexRequest, ::ondewo::nlu::ValidateRegexResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidateRegex_, context, request, response, std::move(f));
}

void Utilities::Stub::async::ValidateRegex(::grpc::ClientContext* context, const ::ondewo::nlu::ValidateRegexRequest* request, ::ondewo::nlu::ValidateRegexResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidateRegex_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ValidateRegexResponse>* Utilities::Stub::PrepareAsyncValidateRegexRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ValidateRegexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::ValidateRegexResponse, ::ondewo::nlu::ValidateRegexRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ValidateRegex_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ValidateRegexResponse>* Utilities::Stub::AsyncValidateRegexRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ValidateRegexRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncValidateRegexRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Utilities::Stub::ValidateEmbeddedRegex(::grpc::ClientContext* context, const ::ondewo::nlu::ValidateEmbeddedRegexRequest& request, ::ondewo::nlu::ValidateEmbeddedRegexResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::ValidateEmbeddedRegexRequest, ::ondewo::nlu::ValidateEmbeddedRegexResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ValidateEmbeddedRegex_, context, request, response);
}

void Utilities::Stub::async::ValidateEmbeddedRegex(::grpc::ClientContext* context, const ::ondewo::nlu::ValidateEmbeddedRegexRequest* request, ::ondewo::nlu::ValidateEmbeddedRegexResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::ValidateEmbeddedRegexRequest, ::ondewo::nlu::ValidateEmbeddedRegexResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidateEmbeddedRegex_, context, request, response, std::move(f));
}

void Utilities::Stub::async::ValidateEmbeddedRegex(::grpc::ClientContext* context, const ::ondewo::nlu::ValidateEmbeddedRegexRequest* request, ::ondewo::nlu::ValidateEmbeddedRegexResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ValidateEmbeddedRegex_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ValidateEmbeddedRegexResponse>* Utilities::Stub::PrepareAsyncValidateEmbeddedRegexRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ValidateEmbeddedRegexRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::ValidateEmbeddedRegexResponse, ::ondewo::nlu::ValidateEmbeddedRegexRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ValidateEmbeddedRegex_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::ValidateEmbeddedRegexResponse>* Utilities::Stub::AsyncValidateEmbeddedRegexRaw(::grpc::ClientContext* context, const ::ondewo::nlu::ValidateEmbeddedRegexRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncValidateEmbeddedRegexRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Utilities::Stub::CleanAllIntents(::grpc::ClientContext* context, const ::ondewo::nlu::CleanAllIntentsRequest& request, ::ondewo::nlu::CleanAllIntentsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::CleanAllIntentsRequest, ::ondewo::nlu::CleanAllIntentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CleanAllIntents_, context, request, response);
}

void Utilities::Stub::async::CleanAllIntents(::grpc::ClientContext* context, const ::ondewo::nlu::CleanAllIntentsRequest* request, ::ondewo::nlu::CleanAllIntentsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::CleanAllIntentsRequest, ::ondewo::nlu::CleanAllIntentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CleanAllIntents_, context, request, response, std::move(f));
}

void Utilities::Stub::async::CleanAllIntents(::grpc::ClientContext* context, const ::ondewo::nlu::CleanAllIntentsRequest* request, ::ondewo::nlu::CleanAllIntentsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CleanAllIntents_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::CleanAllIntentsResponse>* Utilities::Stub::PrepareAsyncCleanAllIntentsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CleanAllIntentsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::CleanAllIntentsResponse, ::ondewo::nlu::CleanAllIntentsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CleanAllIntents_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::CleanAllIntentsResponse>* Utilities::Stub::AsyncCleanAllIntentsRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CleanAllIntentsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCleanAllIntentsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Utilities::Stub::CleanIntent(::grpc::ClientContext* context, const ::ondewo::nlu::CleanIntentRequest& request, ::ondewo::nlu::CleanIntentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::CleanIntentRequest, ::ondewo::nlu::CleanIntentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CleanIntent_, context, request, response);
}

void Utilities::Stub::async::CleanIntent(::grpc::ClientContext* context, const ::ondewo::nlu::CleanIntentRequest* request, ::ondewo::nlu::CleanIntentResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::CleanIntentRequest, ::ondewo::nlu::CleanIntentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CleanIntent_, context, request, response, std::move(f));
}

void Utilities::Stub::async::CleanIntent(::grpc::ClientContext* context, const ::ondewo::nlu::CleanIntentRequest* request, ::ondewo::nlu::CleanIntentResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CleanIntent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::CleanIntentResponse>* Utilities::Stub::PrepareAsyncCleanIntentRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CleanIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::CleanIntentResponse, ::ondewo::nlu::CleanIntentRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CleanIntent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::CleanIntentResponse>* Utilities::Stub::AsyncCleanIntentRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CleanIntentRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCleanIntentRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Utilities::Stub::CleanAllEntityTypes(::grpc::ClientContext* context, const ::ondewo::nlu::CleanAllEntityTypesRequest& request, ::ondewo::nlu::CleanAllEntityTypesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::CleanAllEntityTypesRequest, ::ondewo::nlu::CleanAllEntityTypesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CleanAllEntityTypes_, context, request, response);
}

void Utilities::Stub::async::CleanAllEntityTypes(::grpc::ClientContext* context, const ::ondewo::nlu::CleanAllEntityTypesRequest* request, ::ondewo::nlu::CleanAllEntityTypesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::CleanAllEntityTypesRequest, ::ondewo::nlu::CleanAllEntityTypesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CleanAllEntityTypes_, context, request, response, std::move(f));
}

void Utilities::Stub::async::CleanAllEntityTypes(::grpc::ClientContext* context, const ::ondewo::nlu::CleanAllEntityTypesRequest* request, ::ondewo::nlu::CleanAllEntityTypesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CleanAllEntityTypes_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::CleanAllEntityTypesResponse>* Utilities::Stub::PrepareAsyncCleanAllEntityTypesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CleanAllEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::CleanAllEntityTypesResponse, ::ondewo::nlu::CleanAllEntityTypesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CleanAllEntityTypes_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::CleanAllEntityTypesResponse>* Utilities::Stub::AsyncCleanAllEntityTypesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CleanAllEntityTypesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCleanAllEntityTypesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Utilities::Stub::CleanEntityType(::grpc::ClientContext* context, const ::ondewo::nlu::CleanEntityTypeRequest& request, ::ondewo::nlu::CleanEntityTypeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::CleanEntityTypeRequest, ::ondewo::nlu::CleanEntityTypeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CleanEntityType_, context, request, response);
}

void Utilities::Stub::async::CleanEntityType(::grpc::ClientContext* context, const ::ondewo::nlu::CleanEntityTypeRequest* request, ::ondewo::nlu::CleanEntityTypeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::CleanEntityTypeRequest, ::ondewo::nlu::CleanEntityTypeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CleanEntityType_, context, request, response, std::move(f));
}

void Utilities::Stub::async::CleanEntityType(::grpc::ClientContext* context, const ::ondewo::nlu::CleanEntityTypeRequest* request, ::ondewo::nlu::CleanEntityTypeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CleanEntityType_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::CleanEntityTypeResponse>* Utilities::Stub::PrepareAsyncCleanEntityTypeRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CleanEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::CleanEntityTypeResponse, ::ondewo::nlu::CleanEntityTypeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CleanEntityType_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::CleanEntityTypeResponse>* Utilities::Stub::AsyncCleanEntityTypeRaw(::grpc::ClientContext* context, const ::ondewo::nlu::CleanEntityTypeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCleanEntityTypeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Utilities::Stub::AddTrainingPhrases(::grpc::ClientContext* context, const ::ondewo::nlu::AddTrainingPhrasesRequest& request, ::ondewo::nlu::AddTrainingPhrasesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::AddTrainingPhrasesRequest, ::ondewo::nlu::AddTrainingPhrasesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddTrainingPhrases_, context, request, response);
}

void Utilities::Stub::async::AddTrainingPhrases(::grpc::ClientContext* context, const ::ondewo::nlu::AddTrainingPhrasesRequest* request, ::ondewo::nlu::AddTrainingPhrasesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::AddTrainingPhrasesRequest, ::ondewo::nlu::AddTrainingPhrasesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddTrainingPhrases_, context, request, response, std::move(f));
}

void Utilities::Stub::async::AddTrainingPhrases(::grpc::ClientContext* context, const ::ondewo::nlu::AddTrainingPhrasesRequest* request, ::ondewo::nlu::AddTrainingPhrasesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddTrainingPhrases_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::AddTrainingPhrasesResponse>* Utilities::Stub::PrepareAsyncAddTrainingPhrasesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::AddTrainingPhrasesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::AddTrainingPhrasesResponse, ::ondewo::nlu::AddTrainingPhrasesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddTrainingPhrases_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::AddTrainingPhrasesResponse>* Utilities::Stub::AsyncAddTrainingPhrasesRaw(::grpc::ClientContext* context, const ::ondewo::nlu::AddTrainingPhrasesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddTrainingPhrasesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Utilities::Stub::AddTrainingPhrasesFromCSV(::grpc::ClientContext* context, const ::ondewo::nlu::AddTrainingPhrasesFromCSVRequest& request, ::ondewo::nlu::AddTrainingPhrasesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ondewo::nlu::AddTrainingPhrasesFromCSVRequest, ::ondewo::nlu::AddTrainingPhrasesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddTrainingPhrasesFromCSV_, context, request, response);
}

void Utilities::Stub::async::AddTrainingPhrasesFromCSV(::grpc::ClientContext* context, const ::ondewo::nlu::AddTrainingPhrasesFromCSVRequest* request, ::ondewo::nlu::AddTrainingPhrasesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ondewo::nlu::AddTrainingPhrasesFromCSVRequest, ::ondewo::nlu::AddTrainingPhrasesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddTrainingPhrasesFromCSV_, context, request, response, std::move(f));
}

void Utilities::Stub::async::AddTrainingPhrasesFromCSV(::grpc::ClientContext* context, const ::ondewo::nlu::AddTrainingPhrasesFromCSVRequest* request, ::ondewo::nlu::AddTrainingPhrasesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddTrainingPhrasesFromCSV_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::AddTrainingPhrasesResponse>* Utilities::Stub::PrepareAsyncAddTrainingPhrasesFromCSVRaw(::grpc::ClientContext* context, const ::ondewo::nlu::AddTrainingPhrasesFromCSVRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ondewo::nlu::AddTrainingPhrasesResponse, ::ondewo::nlu::AddTrainingPhrasesFromCSVRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddTrainingPhrasesFromCSV_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ondewo::nlu::AddTrainingPhrasesResponse>* Utilities::Stub::AsyncAddTrainingPhrasesFromCSVRaw(::grpc::ClientContext* context, const ::ondewo::nlu::AddTrainingPhrasesFromCSVRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddTrainingPhrasesFromCSVRaw(context, request, cq);
  result->StartCall();
  return result;
}

Utilities::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Utilities_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Utilities::Service, ::ondewo::nlu::ValidateRegexRequest, ::ondewo::nlu::ValidateRegexResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Utilities::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::ValidateRegexRequest* req,
             ::ondewo::nlu::ValidateRegexResponse* resp) {
               return service->ValidateRegex(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Utilities_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Utilities::Service, ::ondewo::nlu::ValidateEmbeddedRegexRequest, ::ondewo::nlu::ValidateEmbeddedRegexResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Utilities::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::ValidateEmbeddedRegexRequest* req,
             ::ondewo::nlu::ValidateEmbeddedRegexResponse* resp) {
               return service->ValidateEmbeddedRegex(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Utilities_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Utilities::Service, ::ondewo::nlu::CleanAllIntentsRequest, ::ondewo::nlu::CleanAllIntentsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Utilities::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::CleanAllIntentsRequest* req,
             ::ondewo::nlu::CleanAllIntentsResponse* resp) {
               return service->CleanAllIntents(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Utilities_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Utilities::Service, ::ondewo::nlu::CleanIntentRequest, ::ondewo::nlu::CleanIntentResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Utilities::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::CleanIntentRequest* req,
             ::ondewo::nlu::CleanIntentResponse* resp) {
               return service->CleanIntent(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Utilities_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Utilities::Service, ::ondewo::nlu::CleanAllEntityTypesRequest, ::ondewo::nlu::CleanAllEntityTypesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Utilities::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::CleanAllEntityTypesRequest* req,
             ::ondewo::nlu::CleanAllEntityTypesResponse* resp) {
               return service->CleanAllEntityTypes(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Utilities_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Utilities::Service, ::ondewo::nlu::CleanEntityTypeRequest, ::ondewo::nlu::CleanEntityTypeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Utilities::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::CleanEntityTypeRequest* req,
             ::ondewo::nlu::CleanEntityTypeResponse* resp) {
               return service->CleanEntityType(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Utilities_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Utilities::Service, ::ondewo::nlu::AddTrainingPhrasesRequest, ::ondewo::nlu::AddTrainingPhrasesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Utilities::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::AddTrainingPhrasesRequest* req,
             ::ondewo::nlu::AddTrainingPhrasesResponse* resp) {
               return service->AddTrainingPhrases(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Utilities_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Utilities::Service, ::ondewo::nlu::AddTrainingPhrasesFromCSVRequest, ::ondewo::nlu::AddTrainingPhrasesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Utilities::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ondewo::nlu::AddTrainingPhrasesFromCSVRequest* req,
             ::ondewo::nlu::AddTrainingPhrasesResponse* resp) {
               return service->AddTrainingPhrasesFromCSV(ctx, req, resp);
             }, this)));
}

Utilities::Service::~Service() {
}

::grpc::Status Utilities::Service::ValidateRegex(::grpc::ServerContext* context, const ::ondewo::nlu::ValidateRegexRequest* request, ::ondewo::nlu::ValidateRegexResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Utilities::Service::ValidateEmbeddedRegex(::grpc::ServerContext* context, const ::ondewo::nlu::ValidateEmbeddedRegexRequest* request, ::ondewo::nlu::ValidateEmbeddedRegexResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Utilities::Service::CleanAllIntents(::grpc::ServerContext* context, const ::ondewo::nlu::CleanAllIntentsRequest* request, ::ondewo::nlu::CleanAllIntentsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Utilities::Service::CleanIntent(::grpc::ServerContext* context, const ::ondewo::nlu::CleanIntentRequest* request, ::ondewo::nlu::CleanIntentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Utilities::Service::CleanAllEntityTypes(::grpc::ServerContext* context, const ::ondewo::nlu::CleanAllEntityTypesRequest* request, ::ondewo::nlu::CleanAllEntityTypesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Utilities::Service::CleanEntityType(::grpc::ServerContext* context, const ::ondewo::nlu::CleanEntityTypeRequest* request, ::ondewo::nlu::CleanEntityTypeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Utilities::Service::AddTrainingPhrases(::grpc::ServerContext* context, const ::ondewo::nlu::AddTrainingPhrasesRequest* request, ::ondewo::nlu::AddTrainingPhrasesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Utilities::Service::AddTrainingPhrasesFromCSV(::grpc::ServerContext* context, const ::ondewo::nlu::AddTrainingPhrasesFromCSVRequest* request, ::ondewo::nlu::AddTrainingPhrasesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ondewo
}  // namespace nlu

